# Generated by Django 5.2.3 on 2025-12-04 05:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guild",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="2-12个字符",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(12),
                        ],
                        verbose_name="帮会名称",
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=200, verbose_name="帮会简介")),
                (
                    "emblem",
                    models.CharField(
                        default="default", help_text="徽章图标key", max_length=50, verbose_name="帮会徽章"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("level", models.PositiveIntegerField(default=1, verbose_name="帮会等级")),
                ("silver", models.PositiveIntegerField(default=0, verbose_name="银两")),
                ("grain", models.PositiveIntegerField(default=0, verbose_name="粮食")),
                ("gold_bar", models.PositiveIntegerField(default=0, verbose_name="金条")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                ("auto_accept", models.BooleanField(default=False, verbose_name="自动接受申请")),
                (
                    "founder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="founded_guilds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "帮会",
                "verbose_name_plural": "帮会",
                "db_table": "guilds",
                "ordering": ["-level", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuildAnnouncement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("system", "系统公告"), ("leader", "帮主公告")],
                        default="system",
                        max_length=10,
                        verbose_name="公告类型",
                    ),
                ),
                ("content", models.TextField(max_length=500, verbose_name="公告内容")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="发布时间")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布人",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="guilds.guild",
                        verbose_name="所属帮会",
                    ),
                ),
            ],
            options={
                "verbose_name": "帮会公告",
                "verbose_name_plural": "帮会公告",
                "db_table": "guild_announcements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuildApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField(blank=True, max_length=200, verbose_name="申请留言")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="审批时间")),
                ("review_note", models.TextField(blank=True, max_length=200, verbose_name="审批备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="申请时间")),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="guilds.guild",
                        verbose_name="目标帮会",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
            ],
            options={
                "verbose_name": "入帮申请",
                "verbose_name_plural": "入帮申请",
                "db_table": "guild_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuildMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "position",
                    models.CharField(
                        choices=[("leader", "帮主"), ("admin", "管理员"), ("member", "成员")],
                        default="member",
                        max_length=10,
                        verbose_name="职位",
                    ),
                ),
                (
                    "total_contribution",
                    models.PositiveIntegerField(
                        default=0, help_text="历史累计贡献（包括已消费的）", verbose_name="总贡献"
                    ),
                ),
                (
                    "current_contribution",
                    models.PositiveIntegerField(default=0, help_text="可用于兑换的贡献", verbose_name="当前贡献"),
                ),
                (
                    "weekly_contribution",
                    models.PositiveIntegerField(default=0, help_text="每周一0点重置", verbose_name="本周贡献"),
                ),
                ("weekly_reset_at", models.DateField(default=django.utils.timezone.now, verbose_name="本周重置时间")),
                ("joined_at", models.DateTimeField(auto_now_add=True, verbose_name="加入时间")),
                ("last_active_at", models.DateTimeField(auto_now=True, verbose_name="最后活跃时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否在帮")),
                ("left_at", models.DateTimeField(blank=True, null=True, verbose_name="离开时间")),
                ("daily_donation_silver", models.PositiveIntegerField(default=0, verbose_name="今日捐赠银两")),
                ("daily_donation_grain", models.PositiveIntegerField(default=0, verbose_name="今日捐赠粮食")),
                (
                    "daily_donation_reset_at",
                    models.DateField(default=django.utils.timezone.now, verbose_name="每日捐赠重置时间"),
                ),
                ("daily_exchange_count", models.PositiveIntegerField(default=0, verbose_name="今日兑换次数")),
                (
                    "daily_exchange_reset_at",
                    models.DateField(default=django.utils.timezone.now, verbose_name="每日兑换重置时间"),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="guilds.guild",
                        verbose_name="所属帮会",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild_membership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="玩家",
                    ),
                ),
            ],
            options={
                "verbose_name": "帮会成员",
                "verbose_name_plural": "帮会成员",
                "db_table": "guild_members",
                "ordering": ["-position", "-total_contribution"],
                "unique_together": {("guild", "user")},
            },
        ),
        migrations.CreateModel(
            name="GuildExchangeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_key", models.CharField(max_length=100, verbose_name="物品key")),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="兑换数量")),
                ("contribution_cost", models.PositiveIntegerField(verbose_name="消耗贡献")),
                ("exchanged_at", models.DateTimeField(auto_now_add=True, verbose_name="兑换时间")),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_logs",
                        to="guilds.guild",
                        verbose_name="所属帮会",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_logs",
                        to="guilds.guildmember",
                        verbose_name="兑换成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "兑换日志",
                "verbose_name_plural": "兑换日志",
                "db_table": "guild_exchange_logs",
                "ordering": ["-exchanged_at"],
            },
        ),
        migrations.CreateModel(
            name="GuildDonationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("silver", "银两"), ("grain", "粮食")], max_length=10, verbose_name="资源类型"
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="捐赠数量")),
                ("contribution_gained", models.PositiveIntegerField(verbose_name="获得贡献")),
                ("donated_at", models.DateTimeField(auto_now_add=True, verbose_name="捐赠时间")),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation_logs",
                        to="guilds.guild",
                        verbose_name="所属帮会",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation_logs",
                        to="guilds.guildmember",
                        verbose_name="捐赠成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "捐赠日志",
                "verbose_name_plural": "捐赠日志",
                "db_table": "guild_donation_logs",
                "ordering": ["-donated_at"],
            },
        ),
        migrations.CreateModel(
            name="GuildResourceLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("donation", "成员捐赠"),
                            ("tech_upgrade", "科技升级"),
                            ("guild_upgrade", "帮会升级"),
                            ("production", "科技产出"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("silver_change", models.IntegerField(default=0, verbose_name="银两变化")),
                ("grain_change", models.IntegerField(default=0, verbose_name="粮食变化")),
                ("gold_bar_change", models.IntegerField(default=0, verbose_name="金条变化")),
                ("note", models.CharField(blank=True, max_length=200, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="记录时间")),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_logs",
                        to="guilds.guild",
                        verbose_name="所属帮会",
                    ),
                ),
                (
                    "related_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="相关玩家",
                    ),
                ),
            ],
            options={
                "verbose_name": "帮会资源流水",
                "verbose_name_plural": "帮会资源流水",
                "db_table": "guild_resource_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuildTechnology",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tech_key",
                    models.CharField(
                        help_text="如: equipment_forge, military_study", max_length=50, verbose_name="科技标识"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("production", "生产类"), ("combat", "战斗类"), ("welfare", "福利类")],
                        default="production",
                        max_length=20,
                        verbose_name="科技分类",
                    ),
                ),
                ("level", models.PositiveIntegerField(default=0, verbose_name="科技等级")),
                ("max_level", models.PositiveIntegerField(default=5, verbose_name="最高等级")),
                ("last_production_at", models.DateTimeField(blank=True, null=True, verbose_name="最后产出时间")),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="guilds.guild",
                        verbose_name="所属帮会",
                    ),
                ),
            ],
            options={
                "verbose_name": "帮会科技",
                "verbose_name_plural": "帮会科技",
                "db_table": "guild_technologies",
                "unique_together": {("guild", "tech_key")},
            },
        ),
        migrations.CreateModel(
            name="GuildWarehouse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "item_key",
                    models.CharField(help_text="对应ItemTemplate的key", max_length=100, verbose_name="物品key"),
                ),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="数量")),
                ("contribution_cost", models.PositiveIntegerField(default=0, verbose_name="兑换成本（贡献度）")),
                ("total_produced", models.PositiveIntegerField(default=0, verbose_name="总产出数量")),
                ("total_exchanged", models.PositiveIntegerField(default=0, verbose_name="总兑换数量")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_items",
                        to="guilds.guild",
                        verbose_name="所属帮会",
                    ),
                ),
            ],
            options={
                "verbose_name": "帮会仓库",
                "verbose_name_plural": "帮会仓库",
                "db_table": "guild_warehouse",
                "unique_together": {("guild", "item_key")},
            },
        ),
    ]
