# Generated by Django 5.2.8 on 2025-12-31

from django.db import migrations


def _has_column(cursor, table_name: str, column_name: str) -> bool:
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM information_schema.columns
        WHERE table_schema = DATABASE()
          AND table_name = %s
          AND column_name = %s
        """,
        [table_name, column_name],
    )
    return bool(cursor.fetchone()[0])


def _has_table(cursor, table_name: str) -> bool:
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM information_schema.tables
        WHERE table_schema = DATABASE()
          AND table_name = %s
        """,
        [table_name],
    )
    return bool(cursor.fetchone()[0])


def _has_unique_index_on_columns(cursor, table_name: str, columns_csv: str) -> bool:
    cursor.execute(
        """
        SELECT index_name, non_unique,
               GROUP_CONCAT(column_name ORDER BY seq_in_index) AS cols
        FROM information_schema.statistics
        WHERE table_schema = DATABASE()
          AND table_name = %s
        GROUP BY index_name, non_unique
        """,
        [table_name],
    )
    for _, non_unique, cols in cursor.fetchall():
        if int(non_unique) == 0 and (cols or "") == columns_csv:
            return True
    return False


def forwards(apps, schema_editor):
    """
    条件修复 guild_warehouse 表结构：
    - 若缺失 item_key 列，则添加并尽可能从旧的 *_id 列回填
    - 幂等：在正确的数据库上不执行任何操作
    - 仅对 MySQL 执行（生产环境一致）
    """
    conn = schema_editor.connection
    if conn.vendor != "mysql":
        return

    with conn.cursor() as cursor:
        if not _has_table(cursor, "guild_warehouse"):
            return

        if _has_column(cursor, "guild_warehouse", "item_key"):
            return

        # 1) 先添加可空列，避免在回填前触发 NOT NULL 约束
        cursor.execute("ALTER TABLE guild_warehouse ADD COLUMN item_key VARCHAR(100) NULL;")

        # 2) 尝试从旧列回填（历史版本可能是 ForeignKey -> ItemTemplate）
        template_id_column = None
        for candidate in ("item_template_id", "template_id", "item_id"):
            if _has_column(cursor, "guild_warehouse", candidate):
                template_id_column = candidate
                break

        if template_id_column and _has_table(cursor, "gameplay_itemtemplate"):
            cursor.execute(
                f"""
                UPDATE guild_warehouse gw
                LEFT JOIN gameplay_itemtemplate it ON gw.{template_id_column} = it.id
                SET gw.item_key = COALESCE(it.`key`, CONCAT('unknown_', gw.id))
                WHERE gw.item_key IS NULL
                """
            )
        else:
            cursor.execute(
                "UPDATE guild_warehouse SET item_key = CONCAT('unknown_', id) WHERE item_key IS NULL;"
            )

        # 3) 转为 NOT NULL（模型需要）
        cursor.execute("ALTER TABLE guild_warehouse MODIFY COLUMN item_key VARCHAR(100) NOT NULL;")

        # 4) 尽可能补上 unique(guild_id, item_key)（如果已有则跳过）
        if not _has_unique_index_on_columns(cursor, "guild_warehouse", "guild_id,item_key"):
            cursor.execute(
                "ALTER TABLE guild_warehouse "
                "ADD UNIQUE INDEX guildwh_guild_item_key_uniq (guild_id, item_key);"
            )


def backwards(apps, schema_editor):
    """
    回滚：移除 item_key 列（仅用于紧急回滚，不推荐）。
    """
    conn = schema_editor.connection
    if conn.vendor != "mysql":
        return

    with conn.cursor() as cursor:
        if not _has_table(cursor, "guild_warehouse"):
            return
        if not _has_column(cursor, "guild_warehouse", "item_key"):
            return

        # 若存在我们添加的唯一索引则先删除
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
              AND table_name = 'guild_warehouse'
              AND index_name = 'guildwh_guild_item_key_uniq'
            """
        )
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE guild_warehouse DROP INDEX guildwh_guild_item_key_uniq;")

        cursor.execute("ALTER TABLE guild_warehouse DROP COLUMN item_key;")


class Migration(migrations.Migration):
    """
    修复 guild_warehouse 表结构：
    - 线上/旧库可能缺失 item_key 列，导致访问 /guilds/warehouse/ 时报 1054 Unknown column
    - 使用条件 RunPython 同步数据库结构，保持幂等
    - atomic=False：MySQL DDL 会隐式提交事务
    """

    dependencies = [
        ("guilds", "0003_guildmember_guildmember_guild_active_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(
            forwards,
            backwards,
            elidable=False,
            atomic=False,
        ),
    ]
