# Generated by Django 5.2.8 on 2025-12-31

from django.db import migrations


def _has_column(cursor, table_name: str, column_name: str) -> bool:
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM information_schema.columns
        WHERE table_schema = DATABASE()
          AND table_name = %s
          AND column_name = %s
        """,
        [table_name, column_name],
    )
    return bool(cursor.fetchone()[0])


def _has_table(cursor, table_name: str) -> bool:
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM information_schema.tables
        WHERE table_schema = DATABASE()
          AND table_name = %s
        """,
        [table_name],
    )
    return bool(cursor.fetchone()[0])


def forwards(apps, schema_editor):
    """
    条件修复 guild_exchange_logs 表结构：
    - 若缺失 item_key 列，则添加并尽可能从旧的 *_id 列回填
    - 幂等：在正确的数据库上不执行任何操作
    - 仅对 MySQL 执行
    """
    conn = schema_editor.connection
    if conn.vendor != "mysql":
        return

    with conn.cursor() as cursor:
        if not _has_table(cursor, "guild_exchange_logs"):
            return

        if _has_column(cursor, "guild_exchange_logs", "item_key"):
            return

        # 1) 先添加可空列，回填后再改 NOT NULL
        cursor.execute("ALTER TABLE guild_exchange_logs ADD COLUMN item_key VARCHAR(100) NULL;")

        # 2) 尝试从旧列回填（历史版本可能是 ForeignKey -> ItemTemplate）
        template_id_column = None
        for candidate in ("item_template_id", "template_id", "item_id"):
            if _has_column(cursor, "guild_exchange_logs", candidate):
                template_id_column = candidate
                break

        if template_id_column and _has_table(cursor, "gameplay_itemtemplate"):
            cursor.execute(
                f"""
                UPDATE guild_exchange_logs gel
                LEFT JOIN gameplay_itemtemplate it ON gel.{template_id_column} = it.id
                SET gel.item_key = COALESCE(it.`key`, CONCAT('unknown_', gel.id))
                WHERE gel.item_key IS NULL
                """
            )
        else:
            cursor.execute(
                "UPDATE guild_exchange_logs " "SET item_key = CONCAT('unknown_', id) " "WHERE item_key IS NULL;"
            )

        # 3) 转为 NOT NULL（模型需要）
        cursor.execute("ALTER TABLE guild_exchange_logs MODIFY COLUMN item_key VARCHAR(100) NOT NULL;")


def backwards(apps, schema_editor):
    """
    回滚：移除 item_key 列（仅用于紧急回滚，不推荐）。
    """
    conn = schema_editor.connection
    if conn.vendor != "mysql":
        return

    with conn.cursor() as cursor:
        if not _has_table(cursor, "guild_exchange_logs"):
            return
        if not _has_column(cursor, "guild_exchange_logs", "item_key"):
            return
        cursor.execute("ALTER TABLE guild_exchange_logs DROP COLUMN item_key;")


class Migration(migrations.Migration):
    """
    修复 guild_exchange_logs 表结构：
    - 线上/旧库可能缺失 item_key 列，导致访问 /guilds/warehouse/logs/ 时报 1054 Unknown column
    - 使用条件 RunPython 同步数据库结构，保持幂等
    - atomic=False：MySQL DDL 会隐式提交事务
    """

    dependencies = [
        ("guilds", "0004_sync_guild_warehouse_item_key_column"),
    ]

    operations = [
        migrations.RunPython(
            forwards,
            backwards,
            elidable=False,
            atomic=False,
        ),
    ]
