# Generated by Django 5.2.8 on 2026-02-24 04:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0059_alter_recruitmentpool_tier"),
        ("guilds", "0005_sync_guild_exchange_logs_item_key_column"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuildHeroPoolEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slot_index",
                    models.PositiveSmallIntegerField(
                        help_text="每位成员最多2个门客槽位",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="槽位",
                    ),
                ),
                ("snapshot", models.JSONField(blank=True, default=dict, verbose_name="门客快照")),
                ("snapshot_version", models.PositiveSmallIntegerField(default=1, verbose_name="快照版本")),
                (
                    "last_submitted_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="最后提交时间"),
                ),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="过期时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_pool_entries",
                        to="guilds.guild",
                        verbose_name="所属帮会",
                    ),
                ),
                (
                    "owner_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_pool_entries",
                        to="guilds.guildmember",
                        verbose_name="所属成员",
                    ),
                ),
                (
                    "source_guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guild_hero_pool_entries",
                        to="guests.guest",
                        verbose_name="源门客",
                    ),
                ),
            ],
            options={
                "verbose_name": "帮会门客池",
                "verbose_name_plural": "帮会门客池",
                "db_table": "guild_hero_pool_entries",
                "ordering": ["guild_id", "owner_member_id", "slot_index"],
            },
        ),
        migrations.CreateModel(
            name="GuildBattleLineupEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slot_index",
                    models.PositiveSmallIntegerField(
                        help_text="帮会出战名单最多20名",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="出战位",
                    ),
                ),
                ("selected_at", models.DateTimeField(auto_now_add=True, verbose_name="设置时间")),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_lineup_entries",
                        to="guilds.guild",
                        verbose_name="所属帮会",
                    ),
                ),
                (
                    "selected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guild_lineup_selected_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="设置人",
                    ),
                ),
                (
                    "pool_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineup_entries",
                        to="guilds.guildheropoolentry",
                        verbose_name="门客池条目",
                    ),
                ),
            ],
            options={
                "verbose_name": "帮会出战名单",
                "verbose_name_plural": "帮会出战名单",
                "db_table": "guild_battle_lineup_entries",
                "ordering": ["slot_index", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="guildheropoolentry",
            index=models.Index(fields=["guild", "expires_at"], name="ghp_guild_exp_idx"),
        ),
        migrations.AddIndex(
            model_name="guildheropoolentry",
            index=models.Index(fields=["owner_member", "expires_at"], name="ghp_member_exp_idx"),
        ),
        migrations.AddConstraint(
            model_name="guildheropoolentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("slot_index__gte", 1), ("slot_index__lte", 2)), name="ghp_slot_range_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="guildheropoolentry",
            constraint=models.UniqueConstraint(
                fields=("guild", "owner_member", "slot_index"), name="ghp_guild_member_slot_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="guildheropoolentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_guest__isnull", False)),
                fields=("guild", "owner_member", "source_guest"),
                name="ghp_guild_member_guest_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="guildbattlelineupentry",
            index=models.Index(fields=["guild", "selected_at"], name="gbl_guild_sel_idx"),
        ),
        migrations.AddConstraint(
            model_name="guildbattlelineupentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("slot_index__gte", 1), ("slot_index__lte", 20)), name="gbl_slot_range_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="guildbattlelineupentry",
            constraint=models.UniqueConstraint(fields=("guild", "slot_index"), name="gbl_guild_slot_uq"),
        ),
        migrations.AddConstraint(
            model_name="guildbattlelineupentry",
            constraint=models.UniqueConstraint(fields=("guild", "pool_entry"), name="gbl_guild_pool_uq"),
        ),
    ]
