# Generated by Django 5.2.8 on 2026-02-24 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0059_alter_recruitmentpool_tier"),
        ("guilds", "0006_guildheropoolentry_guildbattlelineupentry_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="guildheropoolentry",
            name="ghp_guild_exp_idx",
        ),
        migrations.RemoveIndex(
            model_name="guildheropoolentry",
            name="ghp_member_exp_idx",
        ),
        migrations.RemoveField(
            model_name="guildheropoolentry",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="guildheropoolentry",
            name="snapshot",
        ),
        migrations.RemoveField(
            model_name="guildheropoolentry",
            name="snapshot_version",
        ),
        migrations.AlterField(
            model_name="guildheropoolentry",
            name="source_guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guild_hero_pool_entries",
                to="guests.guest",
                verbose_name="源门客",
            ),
        ),
        migrations.AddIndex(
            model_name="guildheropoolentry",
            index=models.Index(fields=["guild", "owner_member"], name="ghp_guild_member_idx"),
        ),
        migrations.AddIndex(
            model_name="guildheropoolentry",
            index=models.Index(fields=["guild", "last_submitted_at"], name="ghp_guild_submit_idx"),
        ),
    ]
