# Generated by Django 5.2.8 on 2025-12-06 12:56

from django.db import migrations


def forwards(apps, schema_editor):
    """
    条件修复表结构：
    - 若存在错误的 item_template_id 列，先清空表，再删除外键和列，添加正确列和唯一索引
    - 幂等：在正确的数据库上不执行任何操作
    """
    conn = schema_editor.connection
    if conn.vendor != "mysql":
        return
    with conn.cursor() as cursor:
        # 1) 检查是否存在 item_template_id 列
        cursor.execute(
            """
            SELECT COUNT(*) FROM information_schema.columns
            WHERE table_schema = DATABASE()
              AND table_name = 'trade_shop_stock'
              AND column_name = 'item_template_id'
        """
        )
        if cursor.fetchone()[0]:
            # 2) 清空表（数据可丢弃）
            cursor.execute("TRUNCATE TABLE trade_shop_stock;")

            # 3) 如果存在对应的外键约束，先删除外键
            cursor.execute(
                """
                SELECT COUNT(*) FROM information_schema.table_constraints
                WHERE table_schema = DATABASE()
                  AND table_name = 'trade_shop_stock'
                  AND constraint_name = 'trade_shop_stock_item_template_id_8549f92e_fk_gameplay_'
                  AND constraint_type = 'FOREIGN KEY'
            """
            )
            if cursor.fetchone()[0]:
                cursor.execute(
                    "ALTER TABLE trade_shop_stock "
                    "DROP FOREIGN KEY trade_shop_stock_item_template_id_8549f92e_fk_gameplay_;"
                )

            # 4) 删除列、添加新列和唯一索引
            cursor.execute("ALTER TABLE trade_shop_stock DROP COLUMN item_template_id;")
            cursor.execute("ALTER TABLE trade_shop_stock ADD COLUMN item_key VARCHAR(64) NOT NULL;")
            cursor.execute("ALTER TABLE trade_shop_stock ADD UNIQUE INDEX item_key_unique (item_key);")


def backwards(apps, schema_editor):
    """
    回滚操作：恢复到错误的表结构
    （仅用于紧急回滚，不推荐使用）
    """
    conn = schema_editor.connection
    if conn.vendor != "mysql":
        return
    with conn.cursor() as cursor:
        # 检查是否存在 item_key 列
        cursor.execute(
            """
            SELECT COUNT(*) FROM information_schema.columns
            WHERE table_schema = DATABASE()
              AND table_name = 'trade_shop_stock'
              AND column_name = 'item_key'
        """
        )
        if cursor.fetchone()[0]:
            # 清空表并回滚结构
            cursor.execute("TRUNCATE TABLE trade_shop_stock;")
            # 检查索引是否存在再删除
            cursor.execute(
                """
                SELECT COUNT(*) FROM information_schema.statistics
                WHERE table_schema = DATABASE()
                  AND table_name = 'trade_shop_stock'
                  AND index_name = 'item_key_unique'
            """
            )
            if cursor.fetchone()[0]:
                cursor.execute("ALTER TABLE trade_shop_stock DROP INDEX item_key_unique;")
            cursor.execute("ALTER TABLE trade_shop_stock DROP COLUMN item_key;")
            cursor.execute("ALTER TABLE trade_shop_stock ADD COLUMN item_template_id BIGINT;")


class Migration(migrations.Migration):
    """
    修复 trade_shop_stock 表结构：
    - 数据库表错误地包含 item_template_id 列（ForeignKey）
    - 模型定义要求 item_key 列（CharField NOT NULL UNIQUE）
    - 使用条件 RunPython 同步数据库结构，不改变 Django 迁移状态
    - atomic=False 因为 MySQL DDL 会隐式提交事务
    """

    dependencies = [
        ("trade", "0003_marketlisting_markettransaction_and_more"),
    ]

    operations = [
        migrations.RunPython(
            forwards,
            backwards,
            elidable=False,
            atomic=False,  # MySQL DDL 会隐式提交，避免事务问题
        ),
    ]
