# Generated by Django 5.2.8 on 2025-12-06 13:30

import re

from django.db import migrations


# 安全修复：合法的 MySQL 标识符正则（防止 SQL 注入）
VALID_IDENTIFIER_PATTERN = re.compile(r'^[a-zA-Z_][a-zA-Z0-9_]*$')


def _validate_identifier(name: str) -> bool:
    """验证 MySQL 标识符是否合法，防止 SQL 注入"""
    return bool(VALID_IDENTIFIER_PATTERN.match(name)) and len(name) <= 64


def forwards(apps, schema_editor):
    """
    修复 ShopPurchaseLog 和 ShopSellLog 表结构：
    - 数据库表错误地包含 item_template_id 列（ForeignKey）
    - 模型定义要求 item_key 列（CharField）
    """
    conn = schema_editor.connection
    if conn.vendor != "mysql":
        return
    with conn.cursor() as cursor:
        # 修复 trade_shop_purchase_log
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.columns
            WHERE table_schema = DATABASE()
              AND table_name = 'trade_shop_purchase_log'
              AND column_name = 'item_template_id'
        """)
        if cursor.fetchone()[0]:
            # 检查并删除外键约束
            cursor.execute("""
                SELECT constraint_name FROM information_schema.table_constraints
                WHERE table_schema = DATABASE()
                  AND table_name = 'trade_shop_purchase_log'
                  AND constraint_type = 'FOREIGN KEY'
            """)
            fk_names = [row[0] for row in cursor.fetchall()]
            for fk_name in fk_names:
                if 'item_template' in fk_name:
                    # 安全修复：验证标识符防止 SQL 注入
                    if not _validate_identifier(fk_name):
                        raise ValueError(f"Invalid foreign key name: {fk_name}")
                    cursor.execute(f"ALTER TABLE trade_shop_purchase_log DROP FOREIGN KEY {fk_name};")

            # 删除旧列，添加新列
            cursor.execute("ALTER TABLE trade_shop_purchase_log DROP COLUMN item_template_id;")
            cursor.execute("ALTER TABLE trade_shop_purchase_log ADD COLUMN item_key VARCHAR(64) NOT NULL;")

        # 修复 trade_shop_sell_log
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.columns
            WHERE table_schema = DATABASE()
              AND table_name = 'trade_shop_sell_log'
              AND column_name = 'item_template_id'
        """)
        if cursor.fetchone()[0]:
            # 检查并删除外键约束
            cursor.execute("""
                SELECT constraint_name FROM information_schema.table_constraints
                WHERE table_schema = DATABASE()
                  AND table_name = 'trade_shop_sell_log'
                  AND constraint_type = 'FOREIGN KEY'
            """)
            fk_names = [row[0] for row in cursor.fetchall()]
            for fk_name in fk_names:
                if 'item_template' in fk_name:
                    # 安全修复：验证标识符防止 SQL 注入
                    if not _validate_identifier(fk_name):
                        raise ValueError(f"Invalid foreign key name: {fk_name}")
                    cursor.execute(f"ALTER TABLE trade_shop_sell_log DROP FOREIGN KEY {fk_name};")

            # 删除旧列，添加新列
            cursor.execute("ALTER TABLE trade_shop_sell_log DROP COLUMN item_template_id;")
            cursor.execute("ALTER TABLE trade_shop_sell_log ADD COLUMN item_key VARCHAR(64) NOT NULL;")


def backwards(apps, schema_editor):
    """
    回滚操作（不推荐使用）
    """
    conn = schema_editor.connection
    if conn.vendor != "mysql":
        return
    with conn.cursor() as cursor:
        # 回滚 trade_shop_purchase_log
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.columns
            WHERE table_schema = DATABASE()
              AND table_name = 'trade_shop_purchase_log'
              AND column_name = 'item_key'
        """)
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE trade_shop_purchase_log DROP COLUMN item_key;")
            cursor.execute("ALTER TABLE trade_shop_purchase_log ADD COLUMN item_template_id BIGINT;")

        # 回滚 trade_shop_sell_log
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.columns
            WHERE table_schema = DATABASE()
              AND table_name = 'trade_shop_sell_log'
              AND column_name = 'item_key'
        """)
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE trade_shop_sell_log DROP COLUMN item_key;")
            cursor.execute("ALTER TABLE trade_shop_sell_log ADD COLUMN item_template_id BIGINT;")


class Migration(migrations.Migration):
    """
    修复 ShopPurchaseLog 和 ShopSellLog 表结构
    - item_template_id (ForeignKey) -> item_key (CharField)
    - atomic=False 因为 MySQL DDL 会隐式提交
    """

    dependencies = [
        ('trade', '0004_sync_item_key_column'),
    ]

    operations = [
        migrations.RunPython(
            forwards,
            backwards,
            elidable=False,
            atomic=False,
        ),
    ]
