# Generated by Django 5.2.8 on 2025-12-20 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0080_auction_models"),
        ("trade", "0005_fix_purchase_sell_log_item_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionRound",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("round_number", models.PositiveIntegerField(unique=True, verbose_name="轮次编号")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "进行中"), ("settling", "结算中"), ("completed", "已完成")],
                        default="active",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("start_at", models.DateTimeField(verbose_name="开始时间")),
                ("end_at", models.DateTimeField(db_index=True, verbose_name="结束时间")),
                ("settled_at", models.DateTimeField(blank=True, null=True, verbose_name="结算时间")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "拍卖轮次",
                "verbose_name_plural": "拍卖轮次",
                "db_table": "trade_auction_round",
                "ordering": ["-round_number"],
                "indexes": [models.Index(fields=["status", "end_at"], name="trade_aucti_status_1894f3_idx")],
            },
        ),
        migrations.CreateModel(
            name="AuctionSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="数量")),
                ("starting_price", models.PositiveIntegerField(verbose_name="起拍价（金条）")),
                ("current_price", models.PositiveIntegerField(verbose_name="当前最高价（金条）")),
                ("min_increment", models.PositiveIntegerField(default=1, verbose_name="最小加价幅度")),
                ("bid_count", models.PositiveIntegerField(default=0, verbose_name="出价次数")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "竞拍中"), ("sold", "已售出"), ("unsold", "流拍")],
                        default="active",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("config_key", models.CharField(blank=True, max_length=64, verbose_name="配置key")),
                ("slot_index", models.PositiveSmallIntegerField(default=0, verbose_name="同种商品的序号")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "highest_bidder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="highest_bids",
                        to="gameplay.manor",
                        verbose_name="最高出价者",
                    ),
                ),
                (
                    "item_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auction_slots",
                        to="gameplay.itemtemplate",
                        verbose_name="物品模板",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="trade.auctionround",
                        verbose_name="拍卖轮次",
                    ),
                ),
            ],
            options={
                "verbose_name": "拍卖位",
                "verbose_name_plural": "拍卖位",
                "db_table": "trade_auction_slot",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuctionBid",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveIntegerField(verbose_name="出价金额（金条）")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "有效（领先）"),
                            ("outbid", "已被超越"),
                            ("won", "中标"),
                            ("refunded", "已退款"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("frozen_gold_bars", models.PositiveIntegerField(default=0, verbose_name="冻结金条数")),
                ("refunded_at", models.DateTimeField(blank=True, null=True, verbose_name="退款时间")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auction_bids",
                        to="gameplay.manor",
                        verbose_name="出价者",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="trade.auctionslot",
                        verbose_name="拍卖位",
                    ),
                ),
            ],
            options={
                "verbose_name": "出价记录",
                "verbose_name_plural": "出价记录",
                "db_table": "trade_auction_bid",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FrozenGoldBar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveIntegerField(verbose_name="冻结数量")),
                (
                    "reason",
                    models.CharField(choices=[("auction_bid", "拍卖出价")], max_length=32, verbose_name="冻结原因"),
                ),
                ("frozen_at", models.DateTimeField(auto_now_add=True, verbose_name="冻结时间")),
                ("unfrozen_at", models.DateTimeField(blank=True, null=True, verbose_name="解冻时间")),
                ("is_frozen", models.BooleanField(db_index=True, default=True, verbose_name="是否冻结中")),
                (
                    "auction_bid",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frozen_record",
                        to="trade.auctionbid",
                        verbose_name="关联出价",
                    ),
                ),
                (
                    "manor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frozen_gold_bars",
                        to="gameplay.manor",
                        verbose_name="庄园",
                    ),
                ),
            ],
            options={
                "verbose_name": "冻结金条记录",
                "verbose_name_plural": "冻结金条记录",
                "db_table": "trade_frozen_gold_bar",
                "ordering": ["-frozen_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auctionslot",
            index=models.Index(fields=["round", "status"], name="trade_aucti_round_i_6126f3_idx"),
        ),
        migrations.AddIndex(
            model_name="auctionslot",
            index=models.Index(fields=["item_template", "status"], name="trade_aucti_item_te_9e3212_idx"),
        ),
        migrations.AddIndex(
            model_name="auctionbid",
            index=models.Index(fields=["slot", "manor"], name="trade_aucti_slot_id_1d170d_idx"),
        ),
        migrations.AddIndex(
            model_name="auctionbid",
            index=models.Index(fields=["manor", "status"], name="trade_aucti_manor_i_f740e1_idx"),
        ),
        migrations.AddIndex(
            model_name="auctionbid",
            index=models.Index(fields=["status", "created_at"], name="trade_aucti_status_80695c_idx"),
        ),
        migrations.AddIndex(
            model_name="frozengoldbar",
            index=models.Index(fields=["manor", "is_frozen"], name="trade_froze_manor_i_fa75d5_idx"),
        ),
    ]
