# Generated by Django 5.2.8 on 2026-02-06 12:12

from django.db import migrations, models


def populate_status_singleton(apps, schema_editor):
    AuctionRound = apps.get_model("trade", "AuctionRound")

    for status_value in ("active", "settling"):
        qs = AuctionRound.objects.filter(status=status_value)
        count = qs.count()
        if count > 1:
            raise RuntimeError(
                f"Found {count} auction rounds with status={status_value}. "
                "Please keep only one before applying this migration."
            )
        if count == 1:
            qs.update(status_singleton=status_value)


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0006_auction_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionround",
            name="status_singleton",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=16,
                null=True,
                unique=True,
                verbose_name="状态单例锁",
            ),
        ),
        migrations.RunPython(populate_status_singleton, migrations.RunPython.noop),
    ]
