# Generated by Django 5.2.8 on 2025-11-16 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameplay', '0003_backfill_manors'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('slot', models.CharField(choices=[('weapon', '武器'), ('accessory', '饰品')], max_length=16)),
                ('attack_bonus', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('support_bonus', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '装备模板',
                'verbose_name_plural': '装备模板',
            },
        ),
        migrations.CreateModel(
            name='GuestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('archetype', models.CharField(choices=[('civil', '文'), ('military', '武')], max_length=16)),
                ('rarity', models.CharField(choices=[('black', '黑'), ('gray', '灰'), ('green', '绿'), ('blue', '蓝'), ('red', '红'), ('purple', '紫'), ('orange', '橙')], max_length=16)),
                ('base_attack', models.PositiveIntegerField(default=100)),
                ('base_defense', models.PositiveIntegerField(default=100)),
                ('base_support', models.PositiveIntegerField(default=100)),
                ('flavor', models.CharField(blank=True, max_length=128)),
                ('skill_summary', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '门客模板',
                'verbose_name_plural': '门客模板',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('cost', models.JSONField(default=dict)),
                ('cooldown_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '招募卡池',
                'verbose_name_plural': '招募卡池',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('breakthrough', models.PositiveIntegerField(default=0)),
                ('attack_bonus', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('support_bonus', models.IntegerField(default=0)),
                ('morale', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='gameplay.manor')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.guesttemplate')),
            ],
            options={
                'verbose_name': '门客',
                'verbose_name_plural': '门客',
            },
        ),
        migrations.CreateModel(
            name='GearItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('manor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gears', to='gameplay.manor')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.geartemplate')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gear_items', to='guests.guest')),
            ],
            options={
                'verbose_name': '装备实例',
                'verbose_name_plural': '装备实例',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentPoolEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='guests.recruitmentpool')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.guesttemplate')),
            ],
            options={
                'verbose_name': '卡池配置',
                'verbose_name_plural': '卡池配置',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(choices=[('black', '黑'), ('gray', '灰'), ('green', '绿'), ('blue', '蓝'), ('red', '红'), ('purple', '紫'), ('orange', '橙')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.guest')),
                ('manor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruit_records', to='gameplay.manor')),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guests.recruitmentpool')),
            ],
            options={
                'verbose_name': '招募记录',
                'verbose_name_plural': '招募记录',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_level', models.PositiveIntegerField()),
                ('resource_cost', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.guest')),
                ('manor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.manor')),
            ],
            options={
                'verbose_name': '培养记录',
                'verbose_name_plural': '培养记录',
                'ordering': ('-created_at',),
            },
        ),
    ]
