# Generated by Django 5.2.8 on 2025-11-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0010_skills"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="guestskill",
            unique_together={("guest", "skill")},
        ),
    ]
