# Generated by Django 5.2.8 on 2025-11-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0018_guesttemplate_agility_luck"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guesttemplate",
            name="skill_summary",
        ),
    ]
