# Generated by Django 5.2.8 on 2025-11-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0020_recruitmentpoolentry_archetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesttemplate',
            name='recruitable',
            field=models.BooleanField(default=True),
        ),
    ]
