# Generated by Django 5.2.8 on 2025-11-20 14:26

from django.db import migrations, models

RARITY_POWER = {
    "black": 0.8,
    "gray": 1.0,
    "green": 1.2,
    "blue": 1.5,
    "red": 1.9,
    "purple": 2.4,
    "orange": 3.0,
}


def set_initial_hp(apps, schema_editor):
    Guest = apps.get_model("guests", "Guest")
    for guest in Guest.objects.select_related("template").all():
        template = guest.template
        if not template:
            continue
        levels = max(0, getattr(guest, "level", 1) - 1)
        base_hp = template.base_hp + template.hp_growth * levels + guest.hp_bonus
        breakthrough_bonus = template.hp_growth * 5 * getattr(guest, "breakthrough", 0)
        rarity_coeff = RARITY_POWER.get(template.rarity, 1)
        total = max(200, base_hp + breakthrough_bonus)
        guest.current_hp = int(total * rarity_coeff)
        guest.save(update_fields=["current_hp"])


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0021_guesttemplate_recruitable"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="current_hp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="guest",
            name="hp_bonus",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="guest",
            name="skill_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="guesttemplate",
            name="base_hp",
            field=models.PositiveIntegerField(default=1200),
        ),
        migrations.AddField(
            model_name="guesttemplate",
            name="hp_growth",
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="guesttemplate",
            name="initial_skills",
            field=models.ManyToManyField(blank=True, related_name="template_initials", to="guests.skill"),
        ),
        migrations.RunPython(set_initial_hp, migrations.RunPython.noop),
    ]
