# Generated by Django 5.2.8 on 2025-11-20 15:00

from django.db import migrations


def recompute_hp(apps, schema_editor):
    Guest = apps.get_model("guests", "Guest")
    GuestTemplate = apps.get_model("guests", "GuestTemplate")
    templates = {tpl.pk: tpl for tpl in GuestTemplate.objects.all()}
    for guest in Guest.objects.all():
        template = templates.get(guest.template_id)
        if not template:
            continue
        levels = max(0, (guest.level or 1) - 1)
        base_hp = (template.base_hp or 1200) + (template.hp_growth or 0) * levels + (guest.hp_bonus or 0)
        breakthrough_bonus = (template.hp_growth or 0) * 5 * (guest.breakthrough or 0)
        total = max(200, base_hp + breakthrough_bonus)
        guest.current_hp = int(total)
        guest.save(update_fields=["current_hp"])


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0022_guest_current_hp_guest_hp_bonus_guest_skill_points_and_more'),
    ]

    operations = [
        migrations.RunPython(recompute_hp, migrations.RunPython.noop),
    ]
