# Generated by Django 5.2.8 on 2025-11-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0023_recompute_guest_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='damage_formula',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='skill',
            name='required_agility',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='required_defense',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='required_force',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='required_intellect',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='required_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
