# Generated by Django 5.2.8 on 2025-11-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0024_skill_damage_formula_skill_required_agility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="targets",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
