# Generated by Django 5.2.8 on 2025-11-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0025_skill_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('idle', '空闲'), ('working', '打工中'), ('deployed', '出征中'), ('injured', '重伤')], default='idle', max_length=16),
        ),
    ]
