# Generated by Django 5.2.8 on 2025-11-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0034_geartemplate_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='gear_set_bonus',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
