# Generated by Django 5.2.8 on 2025-11-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0035_guest_gear_set_bonus"),
    ]

    operations = [
        migrations.AddField(
            model_name="geartemplate",
            name="set_bonus",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="geartemplate",
            name="set_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
