# Generated by Django 5.2.8 on 2025-11-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0036_geartemplate_set_bonus_geartemplate_set_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="geartemplate",
            name="set_description",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
