# Generated by Django 5.2.3 on 2025-11-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0037_geartemplate_set_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='rarity_revealed',
            field=models.BooleanField(default=False, verbose_name='稀有度已显示'),
        ),
    ]
