# Generated by Django 5.2.3 on 2025-11-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0038_recruitmentcandidate_rarity_revealed"),
    ]

    operations = [
        migrations.AddField(
            model_name="guesttemplate",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="guests/", verbose_name="门客头像"),
        ),
    ]
