# Generated by Django 5.2.3 on 2025-11-30 04:20

from django.db import migrations


def convert_growth_multiplier_to_attributes(apps, schema_editor):
    """
    将成长倍率效果转换为直接属性值。

    这个迁移将现有门客的"隐藏倍率效果"固化到属性值上，
    使得显示的属性值等于实际战斗使用的属性值。
    """
    Guest = apps.get_model("guests", "Guest")

    # 成长率配置（保留用于迁移）
    GROWTH_RATES = {
        "black": 0.07,
        "gray": 0.08,
        "green": 0.09,
        "blue": 0.10,
        "red": 0.11,
        "purple": 0.12,
        "orange": 0.14,
    }

    def calculate_old_multiplier(level, rarity):
        """计算旧系统的成长倍率"""
        growth_rate = GROWTH_RATES.get(rarity, 0.10)

        if level <= 30:
            # 第一阶段：1-30级，全速成长
            return 1 + growth_rate * (level - 1)
        elif level <= 60:
            # 第二阶段：31-60级，60%速度
            base_30 = 1 + growth_rate * 29
            return base_30 + growth_rate * 0.6 * (level - 30)
        else:
            # 第三阶段：61-100级，30%速度
            base_30 = 1 + growth_rate * 29
            base_60 = base_30 + growth_rate * 0.6 * 30
            return base_60 + growth_rate * 0.3 * (level - 60)

    # 统计信息
    total_guests = Guest.objects.count()
    converted_count = 0

    # 遍历所有门客
    for guest in Guest.objects.select_related("template").all():
        multiplier = calculate_old_multiplier(guest.level, guest.template.rarity)

        # 将倍率效果固化到属性上
        guest.force = int(guest.force * multiplier)
        guest.intellect = int(guest.intellect * multiplier)
        guest.defense_stat = int(guest.defense_stat * multiplier)
        guest.agility = int(guest.agility * multiplier)

        guest.save(update_fields=["force", "intellect", "defense_stat", "agility"])
        converted_count += 1

    if converted_count > 0:
        print(f"[OK] 成功转换 {converted_count}/{total_guests} 个门客的属性")
        print("     等级越高的门客属性增幅越大")
    else:
        print("[INFO] 没有需要转换的门客")


def reverse_migration(apps, schema_editor):
    """
    回滚不可行，需要从备份恢复。

    因为我们不知道原始属性值，无法逆向计算。
    """
    raise NotImplementedError(
        "此迁移无法自动回滚。\n"
        "如需回滚，请从数据库备份恢复。\n"
        "备份命令: python manage.py dumpdata guests.Guest > guests_backup.json"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0039_guesttemplate_avatar"),
    ]

    operations = [
        migrations.RunPython(
            convert_growth_multiplier_to_attributes,
            reverse_migration,
        ),
    ]
