# Generated by Django 5.2.8 on 2025-12-08 16:37

from django.db import migrations


NEW_BASE_HP = 1550
NEW_HP_GROWTH = 100
OLD_BASE_HP = 2000
OLD_HP_GROWTH = 140
RARITY = "red"


def compute_max_hp(base_hp, hp_growth, guest):
    """
    计算门客的最大HP。

    公式：max(200, base_hp + hp_growth * (level - 1) + hp_bonus)
    """
    levels = max(0, (getattr(guest, "level", 1) or 1) - 1)
    hp_bonus = getattr(guest, "hp_bonus", 0) or 0
    raw = (base_hp or 0) + (hp_growth or 0) * levels + hp_bonus
    return max(200, raw)


def recompute_current_hp(guest, old_base_hp, old_hp_growth, new_base_hp, new_hp_growth):
    """
    根据模板HP配置变更，重新计算门客的当前HP。

    策略：
    - 如果门客原本满血，更新为新的满血值
    - 如果门客原本受伤，保持相同的受伤比例
    - 确保新的current_hp不超过新的max_hp
    """
    old_max = compute_max_hp(old_base_hp, old_hp_growth, guest)
    new_max = compute_max_hp(new_base_hp, new_hp_growth, guest)
    current = guest.current_hp or 0

    if old_max <= 0:
        return new_max

    # 如果原本满血（或超过满血），直接同步到新满血
    if current >= old_max:
        return new_max

    # 保持相同的受伤比例
    ratio = max(0.0, current / old_max)
    scaled = int(new_max * ratio)
    return max(1, min(new_max, scaled))


def apply_adjustment(apps, target_base_hp, target_hp_growth):
    """
    通用的HP配置调整函数，支持forward和reverse操作。

    Args:
        apps: Django apps registry
        target_base_hp: 目标base_hp值
        target_hp_growth: 目标hp_growth值
    """
    GuestTemplate = apps.get_model("guests", "GuestTemplate")
    Guest = apps.get_model("guests", "Guest")

    # 获取所有红色模板及其当前HP配置
    templates = list(GuestTemplate.objects.filter(rarity=RARITY))
    if not templates:
        return

    # 保存旧的HP配置（在更新前）
    old_state = {tpl.pk: (tpl.base_hp or 0, tpl.hp_growth or 0) for tpl in templates}

    # 批量更新模板HP配置
    GuestTemplate.objects.filter(pk__in=old_state.keys()).update(
        base_hp=target_base_hp,
        hp_growth=target_hp_growth,
    )

    # 获取更新后的配置（用于验证）
    new_state = {
        tpl.pk: (tpl.base_hp or target_base_hp, tpl.hp_growth or target_hp_growth)
        for tpl in GuestTemplate.objects.filter(pk__in=old_state.keys())
    }

    # 重新计算所有相关门客的current_hp
    for guest in Guest.objects.filter(template_id__in=old_state.keys()).select_related("template"):
        old_base_hp, old_hp_growth = old_state.get(guest.template_id, (target_base_hp, target_hp_growth))
        new_base_hp, new_hp_growth = new_state.get(guest.template_id, (target_base_hp, target_hp_growth))

        guest.current_hp = recompute_current_hp(guest, old_base_hp, old_hp_growth, new_base_hp, new_hp_growth)
        guest.save(update_fields=["current_hp"])


def adjust_red_rarity_config(apps, schema_editor):
    """
    调整红色稀有度配置，使其介于绿色和蓝色之间。

    1. 更新红色门客模板的HP配置：base_hp=1550, hp_growth=100
    2. 按比例重新计算所有红色门客的current_hp
    """
    apply_adjustment(apps, NEW_BASE_HP, NEW_HP_GROWTH)


def reverse_adjustment(apps, schema_editor):
    """
    回滚操作：恢复红色稀有度的原始配置。

    使用相同的比例逻辑确保对称性。
    """
    apply_adjustment(apps, OLD_BASE_HP, OLD_HP_GROWTH)


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0041_guestdefection_salarypayment'),
    ]

    operations = [
        migrations.RunPython(adjust_red_rarity_config, reverse_adjustment),
    ]
