# Generated by Django 5.2.8 on 2025-12-09

from django.db import migrations, models
from django.db.models import F


def backfill_intellect_from_defense(apps, schema_editor):
    """
    将现有模板的 base_defense 值复制到 base_intellect 作为临时值。

    这是为了避免在重新加载模板数据前，现有模板的 intellect 为空。
    后续通过 load_guest_templates 命令将使用 attribute_profiles 中的正确值覆盖。
    """
    GuestTemplate = apps.get_model("guests", "GuestTemplate")
    updated_count = GuestTemplate.objects.all().update(base_intellect=F("base_defense"))

    if updated_count > 0:
        print(f"[迁移0043] 已为 {updated_count} 个模板临时填充 base_intellect 值")
        print("           请运行 load_guest_templates 命令加载最终属性值")


def reverse_backfill(apps, schema_editor):
    """回滚操作：无需特殊处理，字段删除会自动清理数据"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0042_adjust_red_rarity_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="guesttemplate",
            name="base_intellect",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.RunPython(
            backfill_intellect_from_defense,
            reverse_backfill,
        ),
    ]
