# Generated by Django 5.2.8 on 2025-12-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0043_add_base_intellect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guesttemplate",
            name="hp_growth",
        ),
    ]
