# Generated by Django 5.2.8 on 2025-12-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0045_rename_skill_points_to_attribute_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='attribute_points',
            field=models.PositiveIntegerField(default=0, verbose_name='属性点'),
        ),
    ]
