# Generated by Django 5.2.8 on 2025-12-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0077_building_building_upgrade_idx_and_more"),
        ("guests", "0047_add_pvp_raid_system"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="guest",
            index=models.Index(fields=["training_complete_at"], name="guest_training_idx"),
        ),
    ]
