# Generated by Django 5.2.8 on 2025-12-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0050_add_template_growth_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesttemplate',
            name='is_hermit',
            field=models.BooleanField(default=False, verbose_name='隐士'),
        ),
    ]
