# Generated by Django 5.2.8 on 2025-12-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0051_add_is_hermit_to_guesttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesttemplate',
            name='flavor',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
