# Generated by Django 5.2.8 on 2025-12-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0053_add_initial_and_allocated_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='xisuidan_used',
            field=models.PositiveIntegerField(default=0, verbose_name='洗髓丹已使用次数'),
        ),
    ]
