# Generated by Django 5.2.8 on 2026-03-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0060_guest_troop_capacity_bonus"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestdefection",
            name="guest_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name="原门客ID"),
        ),
    ]
