# Generated by Django 5.2.8 on 2026-03-24 21:52

from django.db import migrations, models


def migrate_active_arena_guest_statuses(apps, schema_editor):
    Guest = apps.get_model("guests", "Guest")
    ArenaEntryGuest = apps.get_model("gameplay", "ArenaEntryGuest")
    active_guest_ids = list(
        ArenaEntryGuest.objects.filter(
            entry__status="registered",
            entry__tournament__status__in=["recruiting", "running"],
            guest__status="deployed",
        ).values_list("guest_id", flat=True)
    )
    if active_guest_ids:
        Guest.objects.filter(id__in=active_guest_ids, status="deployed").update(status="arena")


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0105_scoutrecord_was_retreated"),
        ("guests", "0061_guestdefection_guest_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "空闲"),
                    ("working", "打工中"),
                    ("deployed", "出征中"),
                    ("arena", "竞技中"),
                    ("injured", "重伤"),
                ],
                default="idle",
                max_length=16,
            ),
        ),
        migrations.RunPython(migrate_active_arena_guest_statuses, migrations.RunPython.noop),
    ]
