"""
游戏核心异常类

提供统一的异常处理机制，替代分散的 ValueError。
每个异常类包含错误代码和用户友好的消息。

使用示例:
    from core.exceptions import InsufficientResourceError, GuestNotIdleError

    if not has_enough_silver(manor, cost):
        raise InsufficientResourceError("silver", cost, manor.silver)

    if guest.status != GuestStatus.IDLE:
        raise GuestNotIdleError(guest)
"""

from .base import GameError
from .building import (
    BuildingError,
    BuildingNotBuiltError,
    BuildingNotFoundError,
    BuildingUpgradingError,
    TechnologyConcurrentUpgradeLimitError,
    TechnologyError,
    TechnologyMaxLevelError,
    TechnologyNotFoundError,
    TechnologyUpgradeInProgressError,
)
from .gameplay import (
    ArenaBusyError,
    ArenaCancellationError,
    ArenaEntryStateError,
    ArenaError,
    ArenaExchangeError,
    ArenaGuestSelectionError,
    ArenaInsufficientCoinsError,
    ArenaParticipationLimitError,
    ArenaRewardLimitError,
    JailError,
    MissionCannotRetreatError,
    MissionDailyLimitError,
    MissionError,
    MissionGuestSelectionError,
    MissionSquadSizeExceededError,
    MissionTroopLoadoutError,
    NoGuestToPayError,
    OathBondAlreadyExistsError,
    OathBondError,
    OathCapacityFullError,
    OathGuestNotFoundError,
    PrisonerAlreadyHandledError,
    PrisonerNotFoundError,
    PrisonerUnavailableError,
    RaidStartError,
    SalaryAlreadyPaidError,
    SalaryError,
    ScoutRetreatStateError,
    ScoutStartError,
    TroopRecruitmentAlreadyInProgressError,
    TroopRecruitmentError,
    WorkError,
    WorkLimitExceededError,
    WorkNotCompletedError,
    WorkNotInProgressError,
    WorkRewardClaimedError,
)
from .guest import (
    GuestError,
    GuestFullHpError,
    GuestInjuredError,
    GuestItemConfigurationError,
    GuestItemOwnershipError,
    GuestMaxLevelError,
    GuestNotFoundError,
    GuestNotIdleError,
    GuestNotRequirementError,
    GuestOwnershipError,
    GuestTrainingInProgressError,
    InvalidHealAmountError,
    NoGuestsError,
)
from .item import (
    DuplicateEquipmentError,
    EquipmentAlreadyEquippedError,
    EquipmentError,
    EquipmentNotEquippedError,
    InsufficientStockError,
    ItemError,
    ItemInsufficientError,
    ItemNotConfiguredError,
    ItemNotFoundError,
    ItemNotUsableError,
)
from .message import (
    AttachmentAlreadyClaimedError,
    AttachmentNotFoundError,
    MessageError,
    MessageNotFoundError,
    NoAttachmentError,
)
from .recruitment import (
    AttributePointError,
    InvalidAllocationError,
    NoTemplateAvailableError,
    PoolNotConfiguredError,
    RecruitmentAlreadyInProgressError,
    RecruitmentCandidateStateError,
    RecruitmentDailyLimitExceededError,
    RecruitmentError,
    RecruitmentItemOwnershipError,
)
from .resource import (
    CapacityError,
    EquipmentSlotFullError,
    GuestCapacityFullError,
    InsufficientResourceError,
    InsufficientSilverError,
    InsufficientSpaceError,
    ResourceError,
    RetainerCapacityFullError,
    SkillSlotFullError,
    TreasuryCapacityFullError,
)
from .trade import ShopValidationError, TradeError, TradeValidationError

__all__ = [
    # Base
    "GameError",
    # Resource & Capacity
    "ResourceError",
    "InsufficientResourceError",
    "InsufficientSilverError",
    "CapacityError",
    "GuestCapacityFullError",
    "RetainerCapacityFullError",
    "SkillSlotFullError",
    "EquipmentSlotFullError",
    "TreasuryCapacityFullError",
    "InsufficientSpaceError",
    # Trade
    "TradeError",
    "TradeValidationError",
    "ShopValidationError",
    # Guest
    "GuestError",
    "GuestNotIdleError",
    "GuestItemOwnershipError",
    "GuestItemConfigurationError",
    "GuestInjuredError",
    "GuestMaxLevelError",
    "GuestTrainingInProgressError",
    "GuestNotFoundError",
    "GuestNotRequirementError",
    "GuestOwnershipError",
    "GuestFullHpError",
    "InvalidHealAmountError",
    "NoGuestsError",
    # Item & Equipment
    "ItemError",
    "ItemNotFoundError",
    "ItemInsufficientError",
    "InsufficientStockError",
    "ItemNotConfiguredError",
    "ItemNotUsableError",
    "EquipmentError",
    "EquipmentAlreadyEquippedError",
    "EquipmentNotEquippedError",
    "DuplicateEquipmentError",
    # Gameplay (Mission, Work, Salary)
    "ArenaError",
    "ArenaGuestSelectionError",
    "ArenaParticipationLimitError",
    "ArenaEntryStateError",
    "ArenaCancellationError",
    "ArenaBusyError",
    "ArenaExchangeError",
    "ArenaInsufficientCoinsError",
    "ArenaRewardLimitError",
    "JailError",
    "MissionError",
    "MissionDailyLimitError",
    "MissionCannotRetreatError",
    "MissionGuestSelectionError",
    "MissionSquadSizeExceededError",
    "MissionTroopLoadoutError",
    "OathBondError",
    "OathGuestNotFoundError",
    "OathCapacityFullError",
    "OathBondAlreadyExistsError",
    "PrisonerUnavailableError",
    "PrisonerNotFoundError",
    "PrisonerAlreadyHandledError",
    "RaidStartError",
    "ScoutStartError",
    "ScoutRetreatStateError",
    "TroopRecruitmentError",
    "TroopRecruitmentAlreadyInProgressError",
    "WorkError",
    "WorkNotInProgressError",
    "WorkNotCompletedError",
    "WorkRewardClaimedError",
    "WorkLimitExceededError",
    "SalaryError",
    "SalaryAlreadyPaidError",
    "NoGuestToPayError",
    # Building & Technology
    "BuildingError",
    "BuildingUpgradingError",
    "BuildingNotBuiltError",
    "BuildingNotFoundError",
    "TechnologyError",
    "TechnologyNotFoundError",
    "TechnologyUpgradeInProgressError",
    "TechnologyConcurrentUpgradeLimitError",
    "TechnologyMaxLevelError",
    # Message
    "MessageError",
    "MessageNotFoundError",
    "AttachmentNotFoundError",
    "AttachmentAlreadyClaimedError",
    "NoAttachmentError",
    # Recruitment & Attribute
    "RecruitmentError",
    "PoolNotConfiguredError",
    "NoTemplateAvailableError",
    "RecruitmentAlreadyInProgressError",
    "RecruitmentDailyLimitExceededError",
    "RecruitmentItemOwnershipError",
    "RecruitmentCandidateStateError",
    "AttributePointError",
    "InvalidAllocationError",
]
