# Generated by Django 5.2.8 on 2025-11-16 10:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=64, verbose_name="建筑名称")),
                ("description", models.TextField(blank=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("wood", "木材"), ("stone", "石料"), ("iron", "铁矿"), ("grain", "粮食")],
                        max_length=16,
                    ),
                ),
                ("base_rate_per_hour", models.PositiveIntegerField(default=50, verbose_name="一级产量(每小时)")),
                ("rate_growth", models.FloatField(default=0.15, verbose_name="每级增长系数")),
                ("base_upgrade_time", models.PositiveIntegerField(default=60, verbose_name="一级建造时间(秒)")),
                ("time_growth", models.FloatField(default=1.25, verbose_name="时间成长系数")),
                ("base_cost", models.JSONField(default=dict)),
                ("cost_growth", models.FloatField(default=1.35, verbose_name="成本成长系数")),
                ("icon", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "verbose_name": "建筑类型",
                "verbose_name_plural": "建筑类型",
            },
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("building_level", "建筑等级"), ("resource_amount", "资源储备")], max_length=32
                    ),
                ),
                ("target_value", models.PositiveIntegerField(default=1)),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        choices=[("wood", "木材"), ("stone", "石料"), ("iron", "铁矿"), ("grain", "粮食")],
                        max_length=16,
                    ),
                ),
                ("reward", models.JSONField(default=dict)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_repeatable", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "任务模版",
                "verbose_name_plural": "任务模版",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Manor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("wood", models.PositiveIntegerField(default=800, verbose_name="木材")),
                ("stone", models.PositiveIntegerField(default=800, verbose_name="石料")),
                ("iron", models.PositiveIntegerField(default=600, verbose_name="铁矿")),
                ("grain", models.PositiveIntegerField(default=1200, verbose_name="粮食")),
                ("storage_capacity", models.PositiveIntegerField(default=20000, verbose_name="仓储上限")),
                ("resource_updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="manor", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "庄园",
                "verbose_name_plural": "庄园",
            },
        ),
        migrations.CreateModel(
            name="ResourceEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("wood", "木材"), ("stone", "石料"), ("iron", "铁矿"), ("grain", "粮食")],
                        max_length=16,
                    ),
                ),
                ("delta", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("produce", "自动产出"),
                            ("upgrade_cost", "建筑升级"),
                            ("task_reward", "任务奖励"),
                            ("admin_adjust", "运营调整"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="resource_events", to="gameplay.manor"
                    ),
                ),
            ],
            options={
                "verbose_name": "资源流水",
                "verbose_name_plural": "资源流水",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.PositiveIntegerField(default=1)),
                ("is_upgrading", models.BooleanField(default=False)),
                ("upgrade_complete_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="gameplay.buildingtype",
                    ),
                ),
                (
                    "manor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="buildings", to="gameplay.manor"
                    ),
                ),
            ],
            options={
                "verbose_name": "建筑",
                "verbose_name_plural": "建筑",
                "unique_together": {("manor", "building_type")},
            },
        ),
        migrations.CreateModel(
            name="TaskProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_value", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="gameplay.manor"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresses",
                        to="gameplay.tasktemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务进度",
                "verbose_name_plural": "任务进度",
                "unique_together": {("manor", "template")},
            },
        ),
    ]
