# Generated by Django 5.2.8 on 2025-11-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0005_seed_silver_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingtype',
            name='resource_type',
            field=models.CharField(choices=[('wood', '木材'), ('stone', '石料'), ('iron', '铁矿'), ('grain', '粮食'), ('silver', '银两')], max_length=16),
        ),
        migrations.AlterField(
            model_name='resourceevent',
            name='reason',
            field=models.CharField(choices=[('produce', '自动产出'), ('upgrade_cost', '建筑升级'), ('task_reward', '任务奖励'), ('admin_adjust', '运营调整'), ('recruit_cost', '门客招募'), ('training_cost', '门客培养')], max_length=32),
        ),
        migrations.AlterField(
            model_name='resourceevent',
            name='resource_type',
            field=models.CharField(choices=[('wood', '木材'), ('stone', '石料'), ('iron', '铁矿'), ('grain', '粮食'), ('silver', '银两')], max_length=16),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('wood', '木材'), ('stone', '石料'), ('iron', '铁矿'), ('grain', '粮食'), ('silver', '银两')], max_length=16),
        ),
    ]
