# Generated by Django 5.2.8 on 2025-11-21 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_battlereport_attacker_troops_and_more'),
        ('gameplay', '0015_retainer_hall'),
        ('guests', '0026_guest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('battle_type', models.CharField(default='task', max_length=32)),
                ('enemy_guests', models.JSONField(blank=True, default=list)),
                ('enemy_troops', models.JSONField(blank=True, default=dict)),
                ('drop_table', models.JSONField(blank=True, default=dict)),
                ('base_travel_time', models.PositiveIntegerField(default=1200, help_text='往返基础耗时（秒）')),
                ('daily_limit', models.PositiveIntegerField(default=3)),
            ],
            options={
                'verbose_name': '任务模板',
                'verbose_name_plural': '任务模板',
            },
        ),
        migrations.CreateModel(
            name='MissionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('troop_loadout', models.JSONField(blank=True, default=dict)),
                ('travel_time', models.PositiveIntegerField(default=0, help_text='单程耗时（秒）')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('return_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '出征中'), ('completed', '已返程')], default='active', max_length=16)),
                ('battle_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle.battlereport')),
                ('guests', models.ManyToManyField(blank=True, related_name='mission_runs', to='guests.guest')),
                ('manor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_runs', to='gameplay.manor')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='gameplay.missiontemplate')),
            ],
            options={
                'verbose_name': '任务出征',
                'verbose_name_plural': '任务出征',
                'ordering': ('-started_at',),
            },
        ),
    ]
