# Generated by ChatGPT
from django.db import migrations


def seed_missions(apps, schema_editor):
    MissionTemplate = apps.get_model("gameplay", "MissionTemplate")
    MissionTemplate.objects.update_or_create(
        key="huashan_lunjian",
        defaults={
            "name": "华山论剑",
            "description": "江湖英雄齐聚华山，以武会友。传闻战胜对手可得传世秘术。",
            "battle_type": "task1",
            "enemy_guests": [
                "special_hero_sao_di_seng",
                "special_hero_dugu_qiubai",
                "special_hero_dongfang_bubai",
            ],
            "enemy_troops": {
                "archer": 1000,
            },
            "drop_table": {
                "silver": 20000,
                "book_dragon_roar": 0.5,
            },
            "base_travel_time": 1200,
            "daily_limit": 3,
        },
    )


def undo_seed(apps, schema_editor):
    MissionTemplate = apps.get_model("gameplay", "MissionTemplate")
    MissionTemplate.objects.filter(key="huashan_lunjian").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0016_missiontemplate_missionrun"),
    ]

    operations = [
        migrations.RunPython(seed_missions, undo_seed, elidable=True),
    ]
