# Generated by ChatGPT
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0017_seed_missions"),
    ]

    operations = [
        migrations.DeleteModel(name="TaskProgress"),
        migrations.DeleteModel(name="TaskTemplate"),
    ]
