# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0018_drop_task_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionrun",
            name="is_retreating",
            field=models.BooleanField(default=False),
        ),
    ]
