# Generated by ChatGPT
from django.db import migrations


def add_tower(apps, schema_editor):
    BuildingType = apps.get_model("gameplay", "BuildingType")
    BuildingType.objects.update_or_create(
        key="youxibaota",
        defaults={
            "name": "悠嘻宝塔",
            "description": "提升同时出征门客人数上限的特殊建筑。",
            "resource_type": "grain",
            "base_rate_per_hour": 0,
            "rate_growth": 0.0,
            "base_upgrade_time": 60,
            "time_growth": 1.2,
            "base_cost": {"wood": 500, "stone": 500, "iron": 300, "grain": 300},
            "cost_growth": 1.3,
            "icon": "",
        },
    )


def remove_tower(apps, schema_editor):
    BuildingType = apps.get_model("gameplay", "BuildingType")
    BuildingType.objects.filter(key="youxibaota").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0019_missionrun_is_retreating"),
    ]

    operations = [
        migrations.RunPython(add_tower, remove_tower, elidable=True),
    ]
