# Generated by Django 5.2.8 on 2025-11-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0021_itemtemplate_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtemplate',
            name='effect_type',
            field=models.CharField(choices=[('resource_pack', '资源补给'), ('skill_book', '技能书'), ('experience_items', '经验道具')], default='resource_pack', max_length=32),
        ),
    ]
