# Generated by Django 5.2.8 on 2025-11-23 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0022_alter_itemtemplate_effect_type"),
        ("gameplay", "0022_itemtemplate_medicine"),
    ]

    operations = []
