# Generated by Django 5.2.3 on 2025-11-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0026_itemtemplate_image_alter_itemtemplate_effect_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.JSONField(blank=True, default=dict, verbose_name='附件数据'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_claimed',
            field=models.BooleanField(default=False, verbose_name='已领取'),
        ),
    ]
