# Generated by Django 5.2.3 on 2025-11-30 07:46

from django.db import migrations


def rename_building(apps, schema_editor):
    """将聚义堂重命名为家丁房"""
    BuildingType = apps.get_model("gameplay", "BuildingType")

    try:
        building_type = BuildingType.objects.get(key="jiadingfang")
        building_type.name = "家丁房"
        building_type.save(update_fields=["name"])
        print(f"[OK] 已将建筑 '{building_type.key}' 重命名为 '家丁房'")
    except BuildingType.DoesNotExist:
        print("[INFO] 未找到 'jiadingfang' 建筑类型，跳过重命名")


def reverse_rename(apps, schema_editor):
    """回滚：将家丁房改回聚义堂"""
    BuildingType = apps.get_model("gameplay", "BuildingType")

    try:
        building_type = BuildingType.objects.get(key="jiadingfang")
        building_type.name = "聚义堂"
        building_type.save(update_fields=["name"])
    except BuildingType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0027_add_message_attachments"),
    ]

    operations = [
        migrations.RunPython(rename_building, reverse_rename),
    ]
