# Generated by Django 5.2.3 on 2025-11-30 07:53

from django.db import migrations


def change_building_key(apps, schema_editor):
    """将建筑类型的 key 从 juyitang 改为 jiadingfang"""
    BuildingType = apps.get_model("gameplay", "BuildingType")

    try:
        building_type = BuildingType.objects.get(key="juyitang")
        building_type.key = "jiadingfang"
        building_type.save(update_fields=["key"])
        print("[OK] 已将建筑类型 key 从 'juyitang' 更改为 'jiadingfang'")
    except BuildingType.DoesNotExist:
        print("[INFO] 未找到 'juyitang' 建筑类型，跳过 key 修改")


def reverse_change_key(apps, schema_editor):
    """回滚：将 key 从 jiadingfang 改回 juyitang"""
    BuildingType = apps.get_model("gameplay", "BuildingType")

    try:
        building_type = BuildingType.objects.get(key="jiadingfang")
        building_type.key = "juyitang"
        building_type.save(update_fields=["key"])
    except BuildingType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0028_rename_juyi_to_jiading"),
    ]

    operations = [
        migrations.RunPython(change_building_key, reverse_change_key),
    ]
