# Generated by Django 5.2.3 on 2025-12-02 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0032_add_technology_upgrade_fields'),
        ('guests', '0040_convert_to_direct_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='工作标识')),
                ('name', models.CharField(max_length=64, verbose_name='工作名称')),
                ('description', models.TextField(blank=True, verbose_name='工作简介')),
                ('tier', models.CharField(choices=[('junior', '初级工作区'), ('intermediate', '中级工作区'), ('senior', '高级工作区')], default='junior', max_length=16, verbose_name='工作区等级')),
                ('required_level', models.PositiveIntegerField(default=1, verbose_name='等级要求')),
                ('required_force', models.PositiveIntegerField(default=0, verbose_name='武力要求')),
                ('required_intellect', models.PositiveIntegerField(default=0, verbose_name='智力要求')),
                ('reward_silver', models.PositiveIntegerField(default=0, verbose_name='银两报酬')),
                ('work_duration', models.PositiveIntegerField(default=7200, verbose_name='工作时长')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='显示顺序')),
                ('icon', models.CharField(blank=True, max_length=32, verbose_name='图标')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '工作模板',
                'verbose_name_plural': '工作模板',
                'ordering': ['tier', 'display_order', 'required_level'],
            },
        ),
        migrations.AlterField(
            model_name='resourceevent',
            name='reason',
            field=models.CharField(choices=[('produce', '自动产出'), ('upgrade_cost', '建筑升级'), ('task_reward', '任务奖励'), ('battle_reward', '战斗掉落'), ('admin_adjust', '运营调整'), ('recruit_cost', '门客招募'), ('training_cost', '门客培养'), ('item_use', '道具使用'), ('shop_purchase', '商铺购买'), ('shop_sell', '商铺出售'), ('work_reward', '打工报酬')], max_length=32),
        ),
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('working', '打工中'), ('completed', '已完成'), ('recalled', '已召回')], default='working', max_length=16, verbose_name='状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('complete_at', models.DateTimeField(verbose_name='完成时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间')),
                ('reward_claimed', models.BooleanField(default=False, verbose_name='已领取报酬')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_assignments', to='guests.guest', verbose_name='门客')),
                ('manor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_assignments', to='gameplay.manor', verbose_name='庄园')),
                ('work_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='gameplay.worktemplate', verbose_name='工作地点')),
            ],
            options={
                'verbose_name': '打工记录',
                'verbose_name_plural': '打工记录',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='gameplay_wo_status_f59fc1_idx'), models.Index(fields=['guest', '-started_at'], name='gameplay_wo_guest_i_ce4e7e_idx')],
            },
        ),
    ]
