# Generated by Django 5.2.3 on 2025-12-02 12:23

from django.db import migrations


def add_treasury_building(apps, schema_editor):
    BuildingType = apps.get_model("gameplay", "BuildingType")
    Building = apps.get_model("gameplay", "Building")
    Manor = apps.get_model("gameplay", "Manor")

    # 创建藏宝阁建筑类型
    treasury, _ = BuildingType.objects.update_or_create(
        key="treasury",
        defaults={
            "name": "藏宝阁",
            "description": "用于安全存储珍贵物品的建筑。藏宝阁中的物品不会被抢夺（trade属性为true的物品除外）。初始容量500，每级增加100容量，最高10级。",
            "resource_type": "silver",
            "base_rate_per_hour": 0,
            "rate_growth": 0.0,
            "base_upgrade_time": 600,
            "time_growth": 1.3,
            "base_cost": {"wood": 1000, "stone": 1000, "iron": 500, "silver": 5000},
            "cost_growth": 1.4,
            "icon": "treasury",
        },
    )

    # 为所有现有庄园创建藏宝阁建筑
    for manor in Manor.objects.all():
        Building.objects.get_or_create(manor=manor, building_type=treasury)


def remove_treasury_building(apps, schema_editor):
    BuildingType = apps.get_model("gameplay", "BuildingType")
    BuildingType.objects.filter(key="treasury").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0034_alter_inventoryitem_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(add_treasury_building, remove_treasury_building, elidable=True),
    ]
