# Generated by Django 5.2.3 on 2025-12-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0035_add_treasury_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtemplate",
            name="is_usable",
            field=models.BooleanField(default=True, verbose_name="可在仓库使用"),
        ),
    ]
