# Generated by Django 5.2.3 on 2025-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0036_itemtemplate_is_usable"),
    ]

    operations = [
        migrations.AddField(
            model_name="missiontemplate",
            name="probability_drop_table",
            field=models.JSONField(blank=True, default=dict, help_text="概率掉落表"),
        ),
    ]
