# Generated by Django 5.2.8 on 2025-12-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0039_message_gameplay_me_manor_i_fdc256_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="missiontemplate",
            name="enemy_technology",
            field=models.JSONField(blank=True, default=dict, help_text="敌方护院科技配置"),
        ),
    ]
