# Generated by Django 5.2.8 on 2025-12-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0041_add_player_troop"),
    ]

    operations = [
        migrations.AddField(
            model_name="manor",
            name="grain_capacity",
            field=models.PositiveIntegerField(default=20000, verbose_name="粮仓上限"),
        ),
        migrations.AddField(
            model_name="manor",
            name="silver_capacity",
            field=models.PositiveIntegerField(default=20000, verbose_name="银库上限"),
        ),
    ]
