# Generated by Django 5.2.8 on 2025-12-12 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0049_remove_resource_production_techs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_key', models.CharField(max_length=64, verbose_name='马匹key')),
                ('horse_name', models.CharField(max_length=64, verbose_name='马匹名称')),
                ('grain_cost', models.PositiveIntegerField(verbose_name='粮食消耗')),
                ('base_duration', models.PositiveIntegerField(verbose_name='基础时长(秒)')),
                ('actual_duration', models.PositiveIntegerField(verbose_name='实际时长(秒)')),
                ('status', models.CharField(choices=[('producing', '生产中'), ('completed', '已完成')], default='producing', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('complete_at', models.DateTimeField(verbose_name='完成时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间')),
                ('manor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horse_productions', to='gameplay.manor')),
            ],
            options={
                'verbose_name': '马匹生产',
                'verbose_name_plural': '马匹生产',
                'ordering': ['-started_at'],
            },
        ),
    ]
