# Generated by Django 5.2.8 on 2025-12-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0050_horse_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseproduction',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='生产数量'),
        ),
    ]
