# Generated by Django 5.2.8 on 2025-12-12 19:19

from django.db import migrations


def update_building_costs(apps, schema_editor):
    """将所有建筑类型的 base_cost 中的 wood/stone/iron 替换为 grain/silver"""
    BuildingType = apps.get_model("gameplay", "BuildingType")

    for bt in BuildingType.objects.all():
        if not bt.base_cost:
            continue

        old_cost = bt.base_cost
        new_cost = {}

        # 将 wood/stone/iron 的费用合并为 silver
        silver_total = old_cost.get("silver", 0)
        silver_total += old_cost.get("wood", 0)
        silver_total += old_cost.get("stone", 0)
        silver_total += old_cost.get("iron", 0)

        if silver_total > 0:
            new_cost["silver"] = silver_total

        # 保留原有的 grain
        if old_cost.get("grain"):
            new_cost["grain"] = old_cost["grain"]

        if new_cost != old_cost:
            bt.base_cost = new_cost
            bt.save(update_fields=["base_cost"])


def reverse_migration(apps, schema_editor):
    """无法反向迁移，跳过"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0053_remove_wood_stone_iron'),
    ]

    operations = [
        migrations.RunPython(update_building_costs, reverse_migration),
    ]
