# Generated by Django 5.2.8 on 2025-12-12 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0054_update_building_costs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmeltingProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_key', models.CharField(max_length=64, verbose_name='金属key')),
                ('metal_name', models.CharField(max_length=64, verbose_name='金属名称')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='冶炼数量')),
                ('silver_cost', models.PositiveIntegerField(verbose_name='银两消耗')),
                ('base_duration', models.PositiveIntegerField(verbose_name='基础时长(秒)')),
                ('actual_duration', models.PositiveIntegerField(verbose_name='实际时长(秒)')),
                ('status', models.CharField(choices=[('producing', '冶炼中'), ('completed', '已完成')], default='producing', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('complete_at', models.DateTimeField(verbose_name='完成时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间')),
                ('manor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smelting_productions', to='gameplay.manor')),
            ],
            options={
                'verbose_name': '金属冶炼',
                'verbose_name_plural': '金属冶炼',
                'ordering': ['-started_at'],
            },
        ),
    ]
