# Generated by Django 5.2.8 on 2025-12-12 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0055_add_smelting_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_key', models.CharField(max_length=64, verbose_name='装备key')),
                ('equipment_name', models.CharField(max_length=64, verbose_name='装备名称')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='锻造数量')),
                ('material_costs', models.JSONField(default=dict, verbose_name='材料消耗')),
                ('base_duration', models.PositiveIntegerField(verbose_name='基础时长(秒)')),
                ('actual_duration', models.PositiveIntegerField(verbose_name='实际时长(秒)')),
                ('status', models.CharField(choices=[('forging', '锻造中'), ('completed', '已完成')], default='forging', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('complete_at', models.DateTimeField(verbose_name='完成时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间')),
                ('manor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_productions', to='gameplay.manor')),
            ],
            options={
                'verbose_name': '装备锻造',
                'verbose_name_plural': '装备锻造',
                'ordering': ['-started_at'],
            },
        ),
    ]
