# Generated by Django 5.2.8 on 2025-12-12 19:45

from django.db import migrations


def update_building_resource_types(apps, schema_editor):
    """
    将已废弃的 wood/stone/iron 资源类型更新为 grain/silver。

    lumber_yard (伐木场) -> grain (粮食，变成粮食生产设施)
    stone_pit (采石场) -> grain
    iron_mine (铁矿) -> silver (银两)
    smithy (铁匠铺) -> silver (锻造收银)
    """
    BuildingType = apps.get_model("gameplay", "BuildingType")

    # 更新映射
    updates = {
        "lumber_yard": "grain",
        "stone_pit": "grain",
        "iron_mine": "silver",
        "smithy": "silver",
    }

    for key, new_resource_type in updates.items():
        BuildingType.objects.filter(key=key).update(resource_type=new_resource_type)


def reverse_update(apps, schema_editor):
    """恢复原来的资源类型"""
    BuildingType = apps.get_model("gameplay", "BuildingType")

    updates = {
        "lumber_yard": "wood",
        "stone_pit": "stone",
        "iron_mine": "iron",
        "smithy": "iron",
    }

    for key, old_resource_type in updates.items():
        BuildingType.objects.filter(key=key).update(resource_type=old_resource_type)


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0057_update_smelting_production_cost_fields"),
    ]

    operations = [
        migrations.RunPython(update_building_resource_types, reverse_update),
    ]
