# Generated by Django 5.2.8 on 2025-12-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0060_remove_lumber_yard_stone_pit"),
    ]

    operations = [
        migrations.AddField(
            model_name="manor",
            name="name",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="庄园名称"),
        ),
    ]
