# Generated by Django 5.2.8 on 2025-12-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0063_troop_recruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='category',
            field=models.CharField(choices=[('resource', '资源生产'), ('storage', '仓储设施'), ('production', '生产加工'), ('personnel', '人员管理'), ('special', '特殊建筑')], default='resource', max_length=16, verbose_name='建筑分类'),
        ),
    ]
