# Generated by Django 5.2.8 on 2025-12-14 07:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0005_add_player_troop"),
        ("gameplay", "0068_remove_iron_mine"),
        ("guests", "0047_add_pvp_raid_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RaidRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("troop_loadout", models.JSONField(blank=True, default=dict, verbose_name="兵种配置")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("marching", "行军中"),
                            ("battling", "战斗中"),
                            ("returning", "返程中"),
                            ("completed", "已完成"),
                            ("retreated", "已撤退"),
                        ],
                        default="marching",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("travel_time", models.PositiveIntegerField(default=0, verbose_name="单程行军时间(秒)")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="出发时间")),
                ("battle_at", models.DateTimeField(blank=True, null=True, verbose_name="战斗时间")),
                ("return_at", models.DateTimeField(blank=True, null=True, verbose_name="返程完成时间")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("loot_resources", models.JSONField(blank=True, default=dict, verbose_name="掠夺资源")),
                ("loot_items", models.JSONField(blank=True, default=dict, verbose_name="掠夺物品")),
                ("attacker_prestige_change", models.IntegerField(default=0, verbose_name="进攻方声望变化")),
                ("defender_prestige_change", models.IntegerField(default=0, verbose_name="防守方声望变化")),
                ("is_retreating", models.BooleanField(default=False, verbose_name="是否撤退中")),
                ("is_attacker_victory", models.BooleanField(blank=True, null=True, verbose_name="进攻方是否胜利")),
            ],
            options={
                "verbose_name": "踢馆出征",
                "verbose_name_plural": "踢馆出征",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ScoutCooldown",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cooldown_until", models.DateTimeField(verbose_name="冷却截止时间")),
            ],
            options={
                "verbose_name": "侦察冷却",
                "verbose_name_plural": "侦察冷却",
            },
        ),
        migrations.CreateModel(
            name="ScoutRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("scouting", "侦察中"), ("success", "侦察成功"), ("failed", "侦察失败")],
                        default="scouting",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("scout_cost", models.PositiveIntegerField(default=1, verbose_name="消耗探子数")),
                ("success_rate", models.FloatField(default=0.5, verbose_name="成功率")),
                ("travel_time", models.PositiveIntegerField(default=60, verbose_name="侦察时间(秒)")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="开始时间")),
                ("complete_at", models.DateTimeField(verbose_name="完成时间")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="实际完成时间")),
                (
                    "intel_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="包含目标庄园的门客、兵力、资源等信息",
                        verbose_name="情报数据",
                    ),
                ),
            ],
            options={
                "verbose_name": "侦察记录",
                "verbose_name_plural": "侦察记录",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="manor",
            name="coordinate_x",
            field=models.PositiveIntegerField(default=0, verbose_name="X坐标"),
        ),
        migrations.AddField(
            model_name="manor",
            name="coordinate_y",
            field=models.PositiveIntegerField(default=0, verbose_name="Y坐标"),
        ),
        migrations.AddField(
            model_name="manor",
            name="defeat_protection_until",
            field=models.DateTimeField(
                blank=True, help_text="被踢馆失败后30分钟保护", null=True, verbose_name="战败保护截止时间"
            ),
        ),
        migrations.AddField(
            model_name="manor",
            name="last_active_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="最后活跃时间"),
        ),
        migrations.AddField(
            model_name="manor",
            name="last_relocation_at",
            field=models.DateTimeField(
                blank=True, help_text="庄园迁移30天冷却", null=True, verbose_name="上次迁移时间"
            ),
        ),
        migrations.AddField(
            model_name="manor",
            name="newbie_protection_until",
            field=models.DateTimeField(
                blank=True, help_text="注册后7天内免受攻击", null=True, verbose_name="新手保护截止时间"
            ),
        ),
        migrations.AddField(
            model_name="manor",
            name="peace_shield_until",
            field=models.DateTimeField(
                blank=True, help_text="使用免战牌后的保护时间", null=True, verbose_name="免战牌保护截止时间"
            ),
        ),
        migrations.AddField(
            model_name="manor",
            name="region",
            field=models.CharField(
                db_index=True, default="overseas", help_text="庄园所在地区编码", max_length=32, verbose_name="地区"
            ),
        ),
        migrations.AddIndex(
            model_name="manor",
            index=models.Index(fields=["region", "coordinate_x", "coordinate_y"], name="gameplay_ma_region_8a1d27_idx"),
        ),
        migrations.AddIndex(
            model_name="manor",
            index=models.Index(fields=["prestige"], name="gameplay_ma_prestig_9cf975_idx"),
        ),
        migrations.AddConstraint(
            model_name="manor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("coordinate_x__gt", 0), ("coordinate_y__gt", 0)),
                fields=("region", "coordinate_x", "coordinate_y"),
                name="unique_manor_location",
            ),
        ),
        migrations.AddField(
            model_name="raidrun",
            name="attacker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raid_runs_sent",
                to="gameplay.manor",
                verbose_name="进攻方",
            ),
        ),
        migrations.AddField(
            model_name="raidrun",
            name="battle_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raid_runs",
                to="battle.battlereport",
                verbose_name="战报",
            ),
        ),
        migrations.AddField(
            model_name="raidrun",
            name="defender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raid_runs_received",
                to="gameplay.manor",
                verbose_name="防守方",
            ),
        ),
        migrations.AddField(
            model_name="raidrun",
            name="guests",
            field=models.ManyToManyField(
                blank=True, related_name="raid_runs", to="guests.guest", verbose_name="出征门客"
            ),
        ),
        migrations.AddField(
            model_name="scoutcooldown",
            name="attacker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="scout_cooldowns_sent", to="gameplay.manor"
            ),
        ),
        migrations.AddField(
            model_name="scoutcooldown",
            name="defender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scout_cooldowns_received",
                to="gameplay.manor",
            ),
        ),
        migrations.AddField(
            model_name="scoutrecord",
            name="attacker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scout_records_sent",
                to="gameplay.manor",
                verbose_name="发起方",
            ),
        ),
        migrations.AddField(
            model_name="scoutrecord",
            name="defender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scout_records_received",
                to="gameplay.manor",
                verbose_name="目标方",
            ),
        ),
        migrations.AddIndex(
            model_name="raidrun",
            index=models.Index(fields=["attacker", "status", "-started_at"], name="gameplay_ra_attacke_0761fa_idx"),
        ),
        migrations.AddIndex(
            model_name="raidrun",
            index=models.Index(fields=["defender", "status", "-started_at"], name="gameplay_ra_defende_37db74_idx"),
        ),
        migrations.AddIndex(
            model_name="raidrun",
            index=models.Index(fields=["status", "battle_at"], name="gameplay_ra_status_e188c3_idx"),
        ),
        migrations.AddIndex(
            model_name="raidrun",
            index=models.Index(fields=["status", "return_at"], name="gameplay_ra_status_fd61a2_idx"),
        ),
        migrations.AddIndex(
            model_name="scoutcooldown",
            index=models.Index(fields=["attacker", "cooldown_until"], name="gameplay_sc_attacke_da46a9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="scoutcooldown",
            unique_together={("attacker", "defender")},
        ),
        migrations.AddIndex(
            model_name="scoutrecord",
            index=models.Index(fields=["attacker", "defender", "-started_at"], name="gameplay_sc_attacke_6b9cc9_idx"),
        ),
        migrations.AddIndex(
            model_name="scoutrecord",
            index=models.Index(fields=["status", "complete_at"], name="gameplay_sc_status_d3c13b_idx"),
        ),
    ]
