# Generated by Django 5.2.8 on 2025-12-15 14:58

from django.db import migrations


def update_youxibaota_config(apps, schema_editor):
    """
    更新悠嘻宝塔配置：
    - 满级从 6 级提升到 15 级
    - 出战人数：0级3人，每级+1人，满级18人
    - 升级成本：14→15级需要2000W银两，指数增长
    - 升级时间：指数增长
    """
    BuildingType = apps.get_model("gameplay", "BuildingType")

    BuildingType.objects.filter(key="youxibaota").update(
        description="登高望远，运筹帷幄。立于塔顶，可观四方风云，调兵遣将，决胜千里。升级提升同时出征门客上限（0级3人，每级+1人，满级15级18人）",
        base_upgrade_time=3107,
        time_growth=1.5,
        base_cost={"grain": 4038, "silver": 20193},
        cost_growth=1.7,
    )


def revert_youxibaota_config(apps, schema_editor):
    """回滚到旧配置"""
    BuildingType = apps.get_model("gameplay", "BuildingType")

    BuildingType.objects.filter(key="youxibaota").update(
        description="登高望远，运筹帷幄。立于塔顶，可观四方风云，调兵遣将，决胜千里。升级提升同时出征门客上限",
        base_upgrade_time=129600,
        time_growth=2.3,
        base_cost={"grain": 10000, "silver": 50000},
        cost_growth=3.3,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0072_update_juxianzhuang_params"),
    ]

    operations = [
        migrations.RunPython(update_youxibaota_config, revert_youxibaota_config),
    ]
