# Generated by Django 5.2.8 on 2025-12-15 15:13

from django.db import migrations


def update_juxianzhuang_config(apps, schema_editor):
    """
    更新聚贤庄配置：
    - 升级成本大幅提升，14→15级需要2000W银两
    - 与悠嘻宝塔保持一致的成本曲线
    """
    BuildingType = apps.get_model("gameplay", "BuildingType")

    BuildingType.objects.filter(key="juxianzhuang").update(
        description="天下英雄，入我彀中。广纳贤才，礼贤下士，方能成就一番霸业。升级提升门客容纳上限（14→15级需要2000W银两）",
        base_upgrade_time=3107,
        time_growth=1.5,
        base_cost={"silver": 20193},
        cost_growth=1.7,
    )


def revert_juxianzhuang_config(apps, schema_editor):
    """回滚到旧配置"""
    BuildingType = apps.get_model("gameplay", "BuildingType")

    BuildingType.objects.filter(key="juxianzhuang").update(
        description="天下英雄，入我彀中。广纳贤才，礼贤下士，方能成就一番霸业。升级提升门客容纳上限",
        base_upgrade_time=3600,
        time_growth=1.46,
        base_cost={"silver": 800},
        cost_growth=1.70,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0074_update_silver_vault_capacity"),
    ]

    operations = [
        migrations.RunPython(update_juxianzhuang_config, revert_juxianzhuang_config),
    ]
