# Generated by Django 5.2.8 on 2025-12-15 15:17

from django.db import migrations


def update_juxianzhuang_config_v2(apps, schema_editor):
    """
    更新聚贤庄配置v2：
    - 添加粮食消耗
    - 成本设计为悠嘻宝塔的85%（略低）
    - 14→15级需要1700W银两+340W粮食
    """
    BuildingType = apps.get_model("gameplay", "BuildingType")

    BuildingType.objects.filter(key="juxianzhuang").update(
        description="天下英雄，入我彀中。广纳贤才，礼贤下士，方能成就一番霸业。升级提升门客容纳上限（14→15级需要1700W银两+340W粮食，成本略低于悠嘻宝塔）",
        base_cost={
            "silver": 17164,
            "grain": 3432
        },
        cost_growth=1.7,
    )


def revert_juxianzhuang_config_v2(apps, schema_editor):
    """回滚到v1配置"""
    BuildingType = apps.get_model("gameplay", "BuildingType")

    BuildingType.objects.filter(key="juxianzhuang").update(
        description="天下英雄，入我彀中。广纳贤才，礼贤下士，方能成就一番霸业。升级提升门客容纳上限（14→15级需要2000W银两）",
        base_cost={
            "silver": 20193
        },
        cost_growth=1.7,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0075_update_juxianzhuang_config'),
    ]

    operations = [
        migrations.RunPython(update_juxianzhuang_config_v2, revert_juxianzhuang_config_v2),
    ]
