# Generated by Django 5.2.8 on 2025-12-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0076_update_juxianzhuang_config_v2"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="building",
            index=models.Index(fields=["manor", "is_upgrading", "upgrade_complete_at"], name="building_upgrade_idx"),
        ),
        migrations.AddIndex(
            model_name="equipmentproduction",
            index=models.Index(fields=["status", "complete_at"], name="equipment_status_complete_idx"),
        ),
        migrations.AddIndex(
            model_name="horseproduction",
            index=models.Index(fields=["status", "complete_at"], name="horse_status_complete_idx"),
        ),
        migrations.AddIndex(
            model_name="livestockproduction",
            index=models.Index(fields=["status", "complete_at"], name="livestock_status_complete_idx"),
        ),
        migrations.AddIndex(
            model_name="playertechnology",
            index=models.Index(fields=["manor", "is_upgrading", "upgrade_complete_at"], name="tech_upgrade_idx"),
        ),
        migrations.AddIndex(
            model_name="smeltingproduction",
            index=models.Index(fields=["status", "complete_at"], name="smelting_status_complete_idx"),
        ),
        migrations.AddIndex(
            model_name="trooprecruitment",
            index=models.Index(fields=["status", "complete_at"], name="troop_status_complete_idx"),
        ),
    ]
