# Generated by Django migration

from django.db import migrations


def unify_tool_effect_types(apps, schema_editor):
    """
    将 magnifying_glass 和 peace_shield 统一为 tool 类型。
    这两种类型本质上都是道具，通过 key 字段区分具体功能。
    """
    ItemTemplate = apps.get_model("gameplay", "ItemTemplate")

    updated = ItemTemplate.objects.filter(effect_type__in=["magnifying_glass", "peace_shield"]).update(
        effect_type="tool"
    )

    if updated:
        print(f"\n  Updated {updated} item template(s) to effect_type='tool'")


def reverse_unify(apps, schema_editor):
    """
    回滚：根据 key 还原原始 effect_type。
    """
    ItemTemplate = apps.get_model("gameplay", "ItemTemplate")

    # 放大镜
    ItemTemplate.objects.filter(key="fangdajing").update(effect_type="magnifying_glass")

    # 免战牌系列
    ItemTemplate.objects.filter(key__startswith="peace_shield_").update(effect_type="peace_shield")


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0078_alter_resourceevent_reason"),
    ]

    operations = [
        migrations.RunPython(unify_tool_effect_types, reverse_unify),
    ]
