# Generated by Django 5.2.8 on 2025-12-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0082_add_mission_extra_attempt"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="raidrun",
            index=models.Index(
                fields=["defender", "-started_at"],
                name="raidrun_def_start_idx",
            ),
        ),
    ]
