# Generated by Django 5.2.8 on 2025-12-31 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0084_alter_itemtemplate_effect_type'),
        ('guests', '0054_add_xisuidan_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='JailPrisoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_guest_name', models.CharField(blank=True, default='', max_length=64, verbose_name='原门客名')),
                ('original_level', models.PositiveIntegerField(default=1, verbose_name='原等级')),
                ('loyalty', models.PositiveIntegerField(default=25, verbose_name='忠诚度')),
                ('status', models.CharField(choices=[('held', '关押中'), ('recruited', '已招募')], db_index=True, default='held', max_length=16, verbose_name='状态')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='俘获时间')),
                ('captor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jail_prisoners', to='gameplay.manor', verbose_name='俘获方')),
                ('guest_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captured_prisoners', to='guests.guesttemplate', verbose_name='门客模板')),
                ('original_manor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_prisoners', to='gameplay.manor', verbose_name='原属庄园')),
                ('raid_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_prisoners', to='gameplay.raidrun', verbose_name='关联踢馆')),
            ],
            options={
                'verbose_name': '监牢囚徒',
                'verbose_name_plural': '监牢囚徒',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['captor', 'status', '-captured_at'], name='jail_captor_status_ca_idx'), models.Index(fields=['original_manor', '-captured_at'], name='jail_orig_ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='OathBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='结义时间')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oath_bond', to='guests.guest', verbose_name='门客')),
                ('manor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oath_bonds', to='gameplay.manor', verbose_name='庄园')),
            ],
            options={
                'verbose_name': '结义关系',
                'verbose_name_plural': '结义关系',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['manor', '-created_at'], name='oathbond_manor_created_idx')],
            },
        ),
    ]
