# Generated by Django 5.2.8 on 2026-02-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0005_add_player_troop"),
        ("gameplay", "0090_alter_resourceevent_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="TroopBankStorage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.PositiveIntegerField(default=0, verbose_name="数量")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="troop_bank_storages",
                        to="gameplay.manor",
                    ),
                ),
                (
                    "troop_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="troop_bank_storages",
                        to="battle.trooptemplate",
                        verbose_name="兵种模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "钱庄护院",
                "verbose_name_plural": "钱庄护院",
                "unique_together": {("manor", "troop_template")},
            },
        ),
    ]
