# Generated by Django 5.2.8 on 2026-02-22 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0005_add_player_troop"),
        ("gameplay", "0091_troopbankstorage"),
        ("guests", "0059_alter_recruitmentpool_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="manor",
            name="arena_coins",
            field=models.PositiveIntegerField(default=0, verbose_name="角斗币"),
        ),
        migrations.CreateModel(
            name="ArenaEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("registered", "参赛中"), ("eliminated", "已淘汰"), ("winner", "冠军")],
                        db_index=True,
                        default="registered",
                        max_length=16,
                    ),
                ),
                ("eliminated_round", models.PositiveIntegerField(blank=True, null=True)),
                ("final_rank", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ("coin_reward", models.PositiveIntegerField(default=0)),
                ("matches_won", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "manor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="arena_entries", to="gameplay.manor"
                    ),
                ),
            ],
            options={
                "verbose_name": "竞技场参赛记录",
                "verbose_name_plural": "竞技场参赛记录",
                "ordering": ("joined_at",),
            },
        ),
        migrations.CreateModel(
            name="ArenaTournament",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recruiting", "报名中"),
                            ("running", "进行中"),
                            ("completed", "已结束"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="recruiting",
                        max_length=16,
                    ),
                ),
                ("player_limit", models.PositiveSmallIntegerField(default=10)),
                ("round_interval_seconds", models.PositiveIntegerField(default=600)),
                ("current_round", models.PositiveIntegerField(default=0)),
                ("next_round_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "winner_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_tournaments",
                        to="gameplay.arenaentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "竞技场赛事",
                "verbose_name_plural": "竞技场赛事",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ArenaMatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("round_number", models.PositiveIntegerField()),
                ("match_index", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "已完成"), ("forfeit", "弃权"), ("bye", "轮空")],
                        default="completed",
                        max_length=16,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attacker_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arena_matches_as_attacker",
                        to="gameplay.arenaentry",
                    ),
                ),
                (
                    "battle_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arena_matches",
                        to="battle.battlereport",
                    ),
                ),
                (
                    "defender_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arena_matches_as_defender",
                        to="gameplay.arenaentry",
                    ),
                ),
                (
                    "winner_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arena_matches_won",
                        to="gameplay.arenaentry",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="gameplay.arenatournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "竞技场对战",
                "verbose_name_plural": "竞技场对战",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="arenaentry",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="gameplay.arenatournament"
            ),
        ),
        migrations.CreateModel(
            name="ArenaEntryGuest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_guests",
                        to="gameplay.arenaentry",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="arena_entry_links", to="guests.guest"
                    ),
                ),
            ],
            options={
                "verbose_name": "竞技场门客报名",
                "verbose_name_plural": "竞技场门客报名",
                "indexes": [models.Index(fields=["entry", "created_at"], name="arena_entry_guest_entry_idx")],
                "constraints": [models.UniqueConstraint(fields=("entry", "guest"), name="unique_arena_entry_guest")],
            },
        ),
        migrations.CreateModel(
            name="ArenaExchangeRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reward_key", models.SlugField(max_length=64)),
                ("reward_name", models.CharField(max_length=128)),
                ("cost_coins", models.PositiveIntegerField(default=0)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "manor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arena_exchange_records",
                        to="gameplay.manor",
                    ),
                ),
            ],
            options={
                "verbose_name": "竞技场兑换记录",
                "verbose_name_plural": "竞技场兑换记录",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["manor", "reward_key", "created_at"], name="arena_ex_manor_reward_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="arenatournament",
            index=models.Index(fields=["status", "next_round_at"], name="arena_tour_status_next_idx"),
        ),
        migrations.AddIndex(
            model_name="arenamatch",
            index=models.Index(fields=["tournament", "round_number"], name="arena_match_tour_round_idx"),
        ),
        migrations.AddIndex(
            model_name="arenamatch",
            index=models.Index(fields=["tournament", "match_index"], name="arena_match_tour_index_idx"),
        ),
        migrations.AddIndex(
            model_name="arenaentry",
            index=models.Index(fields=["manor", "joined_at"], name="arena_entry_manor_joined_idx"),
        ),
        migrations.AddIndex(
            model_name="arenaentry",
            index=models.Index(fields=["tournament", "status"], name="arena_entry_tour_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="arenaentry",
            constraint=models.UniqueConstraint(fields=("tournament", "manor"), name="unique_arena_tournament_manor"),
        ),
    ]
