# Generated by Django 5.2.8 on 2026-02-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0092_arena_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="arenaentryguest",
            name="snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
