# Generated by Django 5.2.8 on 2026-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0093_arena_guest_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionrun",
            name="guest_snapshots",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="raidrun",
            name="guest_snapshots",
            field=models.JSONField(blank=True, default=list, verbose_name="出征门客快照"),
        ),
    ]
