# Generated by Django 5.2.8 on 2026-02-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0094_missionrun_raidrun_guest_snapshots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arenamatch",
            name="status",
            field=models.CharField(
                choices=[("scheduled", "待结算"), ("completed", "已完成"), ("forfeit", "弃权"), ("bye", "轮空")],
                default="completed",
                max_length=16,
            ),
        ),
    ]
