# Generated by Django 5.2.8 on 2026-02-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0095_alter_arenamatch_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="manor",
            name="arena_participation_date",
            field=models.DateField(
                blank=True, db_index=True, default=None, null=True, verbose_name="竞技场参与次数日期"
            ),
        ),
        migrations.AddField(
            model_name="manor",
            name="arena_participations_today",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="竞技场今日参与次数"),
        ),
    ]
