# Generated by Django 5.2.8 on 2026-03-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0102_trooprecruitment_unique_active_per_manor"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="arenatournament",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "recruiting")), fields=("status",), name="unique_recruiting_tournament"
            ),
        ),
    ]
