# Generated by Django 5.2.8 on 2026-03-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0103_arena_unique_recruiting_constraint"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="scoutrecord",
            index=models.Index(fields=["status", "return_at"], name="scout_status_return_at_idx"),
        ),
    ]
