# Generated by Django 5.2.8 on 2026-03-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0104_scout_record_return_at_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoutrecord",
            name="was_retreated",
            field=models.BooleanField(default=False, verbose_name="是否主动撤退"),
        ),
    ]
