from django.urls import path

from .views import (
    AcceptMissionView,
    DashboardView,
    ForgeView,
    MapView,
    MessageListView,
    RaidConfigView,
    RanchView,
    RankingView,
    RecruitmentHallView,
    SettingsView,
    SmithyView,
    StableView,
    TaskBoardView,
    TechnologyView,
    TroopRecruitmentView,
    UpgradeBuildingView,
    WarehouseView,
    WorkView,
    assign_work_view,
    claim_attachment_view,
    claim_work_reward_view,
    manor_detail_api,
    map_search_api,
    protection_status_api,
    raid_status_api,
    recall_work_view,
    rename_manor_view,
    retreat_mission_view,
    retreat_raid_api,
    retreat_scout_view,
    delete_all_messages_view,
    delete_messages_view,
    mark_all_messages_read_view,
    mark_messages_read_view,
    move_item_to_treasury_view,
    move_item_to_warehouse_view,
    start_equipment_forging_view,
    start_horse_production_view,
    start_livestock_production_view,
    start_raid_api,
    start_scout_api,
    start_smelting_production_view,
    start_troop_recruitment_view,
    upgrade_technology_view,
    use_item_view,
    view_message,
)

app_name = "gameplay"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("buildings/<str:category>/", DashboardView.as_view(), name="buildings_category"),
    path("tasks/", TaskBoardView.as_view(), name="tasks"),
    path("messages/", MessageListView.as_view(), name="messages"),
    path("messages/view/<int:pk>/", view_message, name="view_message"),
    path("messages/<int:pk>/claim/", claim_attachment_view, name="claim_attachment"),
    path("messages/delete/", delete_messages_view, name="delete_messages"),
    path("messages/delete-all/", delete_all_messages_view, name="delete_all_messages"),
    path("messages/mark/", mark_messages_read_view, name="mark_messages_read"),
    path("messages/mark-all/", mark_all_messages_read_view, name="mark_all_messages_read"),
    path("warehouse/", WarehouseView.as_view(), name="warehouse"),
    path("warehouse/use/<int:pk>/", use_item_view, name="use_item"),
    path("warehouse/move-to-treasury/<int:pk>/", move_item_to_treasury_view, name="move_to_treasury"),
    path("warehouse/move-to-warehouse/<int:pk>/", move_item_to_warehouse_view, name="move_to_warehouse"),
    path("recruitment/", RecruitmentHallView.as_view(), name="recruitment_hall"),
    path("building/<int:pk>/upgrade/", UpgradeBuildingView.as_view(), name="upgrade_building"),
    path("tasks/accept/", AcceptMissionView.as_view(), name="accept_mission"),
    path("missions/<int:pk>/retreat/", retreat_mission_view, name="mission_retreat"),
    path("technology/", TechnologyView.as_view(), name="technology"),
    path("technology/upgrade/<str:tech_key>/", upgrade_technology_view, name="upgrade_technology"),
    path("work/", WorkView.as_view(), name="work"),
    path("work/assign/", assign_work_view, name="assign_work"),
    path("work/recall/<int:pk>/", recall_work_view, name="recall_work"),
    path("work/claim/<int:pk>/", claim_work_reward_view, name="claim_work_reward"),
    path("stable/", StableView.as_view(), name="stable"),
    path("stable/produce/", start_horse_production_view, name="start_horse_production"),
    path("ranch/", RanchView.as_view(), name="ranch"),
    path("ranch/produce/", start_livestock_production_view, name="start_livestock_production"),
    path("smithy/", SmithyView.as_view(), name="smithy"),
    path("smithy/produce/", start_smelting_production_view, name="start_smelting_production"),
    path("forge/", ForgeView.as_view(), name="forge"),
    path("forge/start/", start_equipment_forging_view, name="start_equipment_forging"),
    path("settings/", SettingsView.as_view(), name="settings"),
    path("settings/rename/", rename_manor_view, name="rename_manor"),
    path("ranking/", RankingView.as_view(), name="ranking"),
    path("troop-recruitment/", TroopRecruitmentView.as_view(), name="troop_recruitment"),
    path("troop-recruitment/start/", start_troop_recruitment_view, name="start_troop_recruitment"),
    # 地图与踢馆系统
    path("map/", MapView.as_view(), name="map"),
    path("map/raid/<int:target_id>/", RaidConfigView.as_view(), name="raid_config"),
    path("api/map/search/", map_search_api, name="map_search_api"),
    path("api/map/manor/<int:manor_id>/", manor_detail_api, name="manor_detail_api"),
    path("api/map/scout/", start_scout_api, name="start_scout_api"),
    path("scout/<int:pk>/retreat/", retreat_scout_view, name="scout_retreat"),
    path("api/map/raid/", start_raid_api, name="start_raid_api"),
    path("api/map/raid/<int:raid_id>/retreat/", retreat_raid_api, name="retreat_raid_api"),
    path("api/map/status/", raid_status_api, name="raid_status_api"),
    path("api/map/protection/", protection_status_api, name="protection_status_api"),
]
