# Generated by Django 5.2.8 on 2025-11-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_battlereport_battle_type_battlereport_drops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlereport',
            name='attacker_troops',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='battlereport',
            name='defender_troops',
            field=models.JSONField(default=dict),
        ),
    ]
